import { SearchType } from "./types/SearchType"

// OBS: jag har även rättat sista albumets label/path och datumformat till ISO (YYYY-MM-DD)
export const searchResults: SearchType = {
  characters: [
        {id: 1, label: "Luna", img: "https://i.pinimg.com/564x/c1/58/41/c158415ece8282618e58a525e51592d9.jpg", actor: "Karol Sevilla", path: "/Luna"},
        {id: 2, label: "Matteo", img: "https://i.pinimg.com/736x/6a/aa/f1/6aaaf1adbf0e841fa0257a352db1d031.jpg", actor: "Ruggero Pasquarelli", path: "/Matteo"},
        {id: 3, label: "Simón", img: "https://pbs.twimg.com/profile_images/782192147793674244/I0H9Ia9N_400x400.jpg", actor: "Michael Ronda", path: "/Simon"},
        {id: 4, label: "Ámbar", img: "https://i.pinimg.com/564x/f3/46/bb/f346bb7dd9e331554633f7cc15e72d59.jpg", actor: "Valentina Zenere", path: "/Ambar"},
        {id: 5, label: "Nina", img: "https://i.pinimg.com/564x/88/72/a2/8872a20dd293eb403e2efb6206e90566.jpg", actor: "Carolina Kopelioff", path: "/Nina"},
        {id: 6, label: "Delfi", img: "https://i.pinimg.com/736x/ca/53/81/ca538152c9e81be9046ee9b6a3a9eeed.jpg", actor: "Malena Ratner", path: "/Delfi"},
        {id: 7, label: "Gastón", img: "https://img.wattpad.com/3e291a72d660402803cef7dccd883b845d5aeff4/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f776174747061642d6d656469612d736572766963652f53746f7279496d6167652f384a6372654d706e5f555f4c70513d3d2d3431323030313537342e313462653835326238316538616233633830333035303130383930332e6a7067?s=fit&w=720&h=720", actor: "Agustìn Bernasconi", path: "/Gastón"},
        {id: 8,  label: "Jazmín", img: "https://i.pinimg.com/474x/d5/f1/5b/d5f15bdcf97948598c92526fce7bf739.jpg", actor: "Katja Martínez", path: "/Jazmín"},
        {id: 9, label: "Jim", img: "https://i.pinimg.com/564x/d1/fb/f9/d1fbf97052e502657c3d99a9c4f854f7.jpg", actor: "Ana Jara", path: "/Jim"},
        {id: 10, label: "Yam", img: "https://i.pinimg.com/474x/99/20/4a/99204a7ddc1e80b9289d460df7046a14.jpg", actor: "Chiara Parravicini", path: "/Yam"},
        {id: 11, label: "Ramiro", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRjUIZ2hYuSBkVMxmSRHNKOx4WkG1cXGJek5g&s", actor: "Jorge López", path: "/Ramiro"},
        {id: 12, label: "Pedro", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTb3mT6g6di-cZYgxGWAAdXiM4XNYEF67FLNmZ5vcpLjht0h5PgU9ELCsNPnGWKOb4rBn8&usqp=CAU", actor: "Gastón Vietto", path: "/Pedro"},
        {id: 13, label: "Nico", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTHwqrTXcJ8cN3hc4kbzx1tfn5H5sDjtj3NyJPHj5mu5oSWCiRYqQNvJ4s23dPq2hojV94&usqp=CAU", actor: "Lionel Ferro", path: "/Nico"},
        {id: 14, label: "Tamara", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTA9VssqUHjDcsImv5kA7TG8ir_3BXcC8QB-A&s", actor: "Luz Capriota", path: "/Tamara"},
        {id: 15, label: "Mrs. Benson", img: "https://pbs.twimg.com/profile_images/896031069849497601/mFX48SWF_400x400.jpg", actor: "Lucila Gandolfo", path: "/Sharon"},
        {id: 16, label: "Rey", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQeTnM8jeVkNkCO0yXhd6dwZYQ1O-fZYq8Idg&s", actor: "Rodrigo Pedreira", path: "/Rey"},
        {id: 17, label: "Miguel", img: "https://tiermaker.com/images/chart/chart/soy-luna-characters-520944/migueljpg.png", actor: "David Muri", path: "/Miguel"},
        {id: 18, label: "Mónica", img: "https://assets.puzzlefactory.com/puzzle/352/239/original.jpg", actor: "Ana Carolina Valsagna", path: "/Mónica"},
        {id: 19, label: "Tino", img: "src/assets/Tino.jpg", actor: "Diego Sassi Alcalá", path: "/Tino"},
        {id: 20, label: "Cato", img: "src/assets/Cato.jpg", actor: "Germán Tripel", path: "/Cato"},
        {id: 21, label: "Amanda", img: "src/assets/Amanda.jpg", actor: "Antonella Querzoli", path: "/Amanda"},
        {id: 22, label: "Ricardo", img: "src/assets/ricardo.jpg", actor: "Ezequiel Rodríquez", path: "/Ricardo"},
        {id: 23, label: "Ana", img: "src/assets/ana.jpg", actor: "Caro Ibarro", path: "/Ana"},
        {id: 24, label: "Mora", img: "src/assets/mora.jpg", actor: "Paula Kohan", path: "/Mora"},
        {id: 25, label: "Juliana", img: "src/assets/juliana.jpg", actor: "Estela Ribeiro", path: "/Juliana"},
        {id: 26, label: "Alfredo", img: "src/assets/alfredo.jpg", actor: "Roberto Carnaghi", path: "/Alfredo"},
        {id: 27, label: "Gary", img: "https://vignette.wikia.nocookie.net/soyluna/images/b/bd/Gary.jpg/revision/latest?cb=20200625095218", actor: "Joaquín Berthold", path: "/Gary"},
        {id: 28, label: "Benicio", img: "src/assets/benicio.jpg", actor: "Pasquale Di Nuzzo", path: "/Benicio"},
        {id: 29, label: "Emilia", img: "https://i.pinimg.com/736x/a6/ea/20/a6ea2069ff3aef1a27e5f6c098d7ba97.jpg", actor: "Giovanna Reynaud", path: "/Emila"},
        {id: 30, label: "Eric", img: "src/assets/eric.jpg", actor: "Jandino", path: "/Eric"},
        {id: 31, label: "Maggie", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRitLGbjcYLFLEPC3W2dUF_AUMIFrXS13c0jg&s", actor: "Victoria Suárez Battán", path: "/Maggie"}
    ],
  seasons: [
    {id: 1, label: "Season 1", path: "/Season_1"},
    {id: 2, label: "Season 2", path: "/Season_2"},
    {id: 3, label: "Season 3", path: "/Season_3"},
    {id: 4, label: "Season 4", path: "/Season_4"}
  ],
  albums: [
    {id:1, img:"https://upload.wikimedia.org/wikipedia/en/0/04/Soy_Luna_soundtrack.jpg", path:"/Soy_Luna (Album)", label:"Soy Luna (Album)", season:1, nosongs:12, release:"2016-02-26"},
    {id:2, img:"https://upload.wikimedia.org/wikipedia/en/0/0b/Soy_Luna_-_M%C3%BAsica_en_ti.jpg", path:"/Musica_en_ti (Album)", label:"Música en ti (Album)", season:1, nosongs:13, release:"2016-08-26"},
    {id:3, img:"https://upload.wikimedia.org/wikipedia/en/4/40/La_vida_es_un_sue%C3%B1o.jpg", path:"/La_vida_es_un_sueño (Album)", label:"La vida es un sueño part 1 & 2 (Album)", season:2, nosongs:25, release:"2017-03-03"},
    // här var label/path omkastade – fixat nedan:
    {id:4, img:"https://i.scdn.co/image/ab67616d0000b273effbb11a16be922e05017e98", path:"/Modo_Amar (Album)", label:"Modo Amar (Album)", season:3, nosongs:19, release:"2018-04-06"}
  ],
  songs: {
    albumOne: [
        { id: 1,  label: "Alas",              artist: "Karol Sevilla",                                   release: "2016-02-26", season: 1, album: "Soy Luna", img: "", spotifyUrl: "", ytUrl: "" },
        { id: 2,  label: "Valiente",          artist: "Michael Ronda",                                   release: "2016-02-26", season: 1, album: "Soy Luna", img: "", spotifyUrl: "", ytUrl: "" },
        { id: 3,  label: "Eres",              artist: "Karol Sevilla & Michael Ronda",                   release: "2016-02-26", season: 1, album: "Soy Luna", img: "", spotifyUrl: "", ytUrl: "" },
        { id: 4,  label: "Prófugos",          artist: "Ruggero Pasquarelli & Valentina Zenere",          release: "2016-02-26", season: 1, album: "Soy Luna", img: "", spotifyUrl: "", ytUrl: "" },
        { id: 5,  label: "Un destino",        artist: "Michael Ronda, Lionel Ferro & Gastón Vietto",     release: "2016-02-26", season: 1, album: "Soy Luna", img: "", spotifyUrl: "", ytUrl: "" },
        { id: 6,  label: "Sobre ruedas",      artist: "Female Cast",                                     release: "2016-02-26", season: 1, album: "Soy Luna", img: "", spotifyUrl: "", ytUrl: "" },
        { id: 7,  label: "Corazón",           artist: "Agustín Bernasconi & Malena Ratner",              release: "2016-02-26", season: 1, album: "Soy Luna", img: "", spotifyUrl: "", ytUrl: "" },
        { id: 8,  label: "Mírame a mí",       artist: "Valentina Zenere",                                release: "2016-02-26", season: 1, album: "Soy Luna", img: "", spotifyUrl: "", ytUrl: "" },
        { id: 9,  label: "I'd Be Crazy",      artist: "Male Cast",                                       release: "2016-02-26", season: 1, album: "Soy Luna", img: "", spotifyUrl: "", ytUrl: "" },
        { id:10,  label: "Siento",            artist: "Ruggero Pasquarelli",                             release: "2016-02-26", season: 1, album: "Soy Luna", img: "", spotifyUrl: "", ytUrl: "" },
        { id:11,  label: "Invisibles",        artist: "Michael Ronda, Lionel Ferro & Gastón Vietto",     release: "2016-02-26", season: 1, album: "Soy Luna", img: "", spotifyUrl: "", ytUrl: "" },
        { id:12,  label: "Camino",            artist: "Cast",                                            release: "2016-02-26", season: 1, album: "Soy Luna", img: "", spotifyUrl: "", ytUrl: "" },
    ],
    albumTwo: [
        { id:13,  label: "Vuelo",             artist: "Cast",                                            release: "2016-08-26", season: 1, album: "Música en ti", img: "", spotifyUrl: "", ytUrl: "" },
        { id:14,  label: "Música en ti",                  artist: "Karol Sevilla",                                       release: "2016-08-26", season: 1, album: "Música en ti", img: "", spotifyUrl: "", ytUrl: "" },
        { id:15,  label: "A rodar mi vida",               artist: "Cast",                                                release: "2016-08-26", season: 1, album: "Música en ti", img: "", spotifyUrl: "", ytUrl: "" },
        { id:16,  label: "Nada ni nadie",                 artist: "Ruggero Pasquarelli",                                 release: "2016-08-26", season: 1, album: "Música en ti", img: "", spotifyUrl: "", ytUrl: "" },
        { id:17,  label: "Chicas así",                    artist: "Valentina Zenere, Malena Ratner & Katja Martínez",    release: "2016-08-26", season: 1, album: "Música en ti", img: "", spotifyUrl: "", ytUrl: "" },
        { id:18,  label: "Tengo un corazón",              artist: "Carolina Kopelioff",                                   release: "2016-08-26", season: 1, album: "Música en ti", img: "", spotifyUrl: "", ytUrl: "" },
        { id:19,  label: "Qué más da",                    artist: "Karol Sevilla & Ruggero Pasquarelli",                 release: "2016-08-26", season: 1, album: "Música en ti", img: "", spotifyUrl: "", ytUrl: "" },
        { id:20,  label: "Sin fronteras",                 artist: "Karol Sevilla & Carolina Kopelioff",                  release: "2016-08-26", season: 1, album: "Música en ti", img: "", spotifyUrl: "", ytUrl: "" },
        { id:21,  label: "Eres (Radio Disney Vivo)",      artist: "Karol Sevilla, Ruggero Pasquarelli & Michael Ronda",  release: "2016-08-26", season: 1, album: "Música en ti", img: "", spotifyUrl: "", ytUrl: "" },
        { id:22,  label: "Valiente (Radio Disney Vivo)",  artist: "Karol Sevilla, Michael Ronda, Gastón Vietto & Lionel Ferro", release: "2016-08-26", season: 1, album: "Música en ti", img: "", spotifyUrl: "", ytUrl: "" },
        { id:23,  label: "Alas (Radio Disney Vivo)",      artist: "Cast",                                                release: "2016-08-26", season: 1, album: "Música en ti", img: "", spotifyUrl: "", ytUrl: "" },
        { id:24,  label: "A rodar mi vida (Acoustic)",    artist: "Chiara Parravicini",                                   release: "2016-08-26", season: 1, album: "Música en ti", img: "", spotifyUrl: "", ytUrl: "" },
    ],
    albumThree:[
        { id:25,  label: "Siempre juntos",       artist: "Karol Sevilla",                                       release: "2017-03-03", season: 2, album: "La vida es un sueño", img: "", spotifyUrl: "", ytUrl: "" },
        { id:26,  label: "Alzo mi bandera",      artist: "Michael Ronda, Gastón Vietto & Lionel Ferro",         release: "2017-03-03", season: 2, album: "La vida es un sueño", img: "", spotifyUrl: "", ytUrl: "" },
        { id:27,  label: "La vida es un sueño",  artist: "Karol Sevilla",                                       release: "2017-03-03", season: 2, album: "La vida es un sueño", img: "", spotifyUrl: "", ytUrl: "" },
        { id:28,  label: "Fush, ¡Te vas!",       artist: "Katja Martínez",                                      release: "2017-03-03", season: 2, album: "La vida es un sueño", img: "", spotifyUrl: "", ytUrl: "" },
        { id:29,  label: "¿Cómo me ves?",        artist: "Valentina Zenere",                                    release: "2017-03-03", season: 2, album: "La vida es un sueño", img: "", spotifyUrl: "", ytUrl: "" },
        { id:30,  label: "Mitad y mitad",        artist: "Agustín Bernasconi & Carolina Kopelioff",             release: "2017-03-03", season: 2, album: "La vida es un sueño", img: "", spotifyUrl: "", ytUrl: "" },
        { id:31,  label: "Valiente",             artist: "Cast",                                                release: "2017-03-03", season: 2, album: "La vida es un sueño", img: "", spotifyUrl: "", ytUrl: "" },
        { id:32,  label: "Honey Funny",          artist: "Chiara Parravicini, Ana Jara & Jorge López",          release: "2017-03-03", season: 2, album: "La vida es un sueño", img: "", spotifyUrl: "", ytUrl: "" },
        { id:33,  label: "Linda",                artist: "Michael Ronda, Gastón Vietto & Lionel Ferro",         release: "2017-03-03", season: 2, album: "La vida es un sueño", img: "", spotifyUrl: "", ytUrl: "" },
        { id:34,  label: "Cuenta conmigo",       artist: "Cast",                                                release: "2017-03-03", season: 2, album: "La vida es un sueño", img: "", spotifyUrl: "", ytUrl: "" },
        { id:35,  label: "Vives en mí",          artist: "Karol Sevilla & Ruggero Pasquarelli",                 release: "2017-03-03", season: 2, album: "La vida es un sueño", img: "", spotifyUrl: "", ytUrl: "" },
        { id:36,  label: "I've Got a Feeling",   artist: "Cast",                                                release: "2017-03-03", season: 2, album: "La vida es un sueño", img: "", spotifyUrl: "", ytUrl: "" },
        { id:37,  label: "Princesa",             artist: "Ruggero Pasquarelli",                                 release: "2017-03-03", season: 2, album: "La vida es un sueño", img: "", spotifyUrl: "", ytUrl: "" },
        // Disc 2
        { id:38,  label: "Footloose",            artist: "Cast",                                                release: "2017-03-03", season: 2, album: "La vida es un sueño", img: "", spotifyUrl: "", ytUrl: "" },
        { id:39,  label: "Sólo para ti",         artist: "Karol Sevilla",                                       release: "2017-03-03", season: 2, album: "La vida es un sueño", img: "", spotifyUrl: "", ytUrl: "" },
        { id:40,  label: "Catch Me If You Can",  artist: "Valentina Zenere",                                    release: "2017-03-03", season: 2, album: "La vida es un sueño", img: "", spotifyUrl: "", ytUrl: "" },
        { id:41,  label: "Pienso",               artist: "Michael Ronda, Gastón Vietto & Lionel Ferro",         release: "2017-03-03", season: 2, album: "La vida es un sueño", img: "", spotifyUrl: "", ytUrl: "" },
        { id:42,  label: "Andaremos",            artist: "Karol Sevilla & Michael Ronda",                       release: "2017-03-03", season: 2, album: "La vida es un sueño", img: "", spotifyUrl: "", ytUrl: "" },
        { id:43,  label: "Allá voy",             artist: "Ruggero Pasquarelli",                                 release: "2017-03-03", season: 2, album: "La vida es un sueño", img: "", spotifyUrl: "", ytUrl: "" },
        { id:44,  label: "No te pido mucho",     artist: "Karol Sevilla",                                       release: "2017-03-03", season: 2, album: "La vida es un sueño", img: "", spotifyUrl: "", ytUrl: "" },
        { id:45,  label: "Stranger",             artist: "Ruggero Pasquarelli",                                 release: "2017-03-03", season: 2, album: "La vida es un sueño", img: "", spotifyUrl: "", ytUrl: "" },
        { id:46,  label: "Aquí estoy",           artist: "Agustín Bernasconi & Ruggero Pasquarelli",            release: "2017-03-03", season: 2, album: "La vida es un sueño", img: "", spotifyUrl: "", ytUrl: "" },
        { id:48,  label: "Yo quisiera",          artist: "Michael Ronda",                                       release: "2017-03-03", season: 2, album: "La vida es un sueño", img: "", spotifyUrl: "", ytUrl: "" },
        { id:49,  label: "Siempre juntos (group version)", artist: "Cast",                                      release: "2017-03-03", season: 2, album: "La vida es un sueño", img: "", spotifyUrl: "", ytUrl: "" },
        ],
    albumFour: [
        { id:50,  label: "Modo amar",                 artist: "Cast",                                                                 release: "2018-04-06", season: 3, album: "Modo amar", img: "", spotifyUrl: "", ytUrl: "" },
        { id:51,  label: "Soy yo",                    artist: "Karol Sevilla",                                                       release: "2018-04-06", season: 3, album: "Modo amar", img: "", spotifyUrl: "", ytUrl: "" },
        { id:52,  label: "Quiero verte sonreir",      artist: "Ruggero Pasquarelli",                                                 release: "2018-04-06", season: 3, album: "Modo amar", img: "", spotifyUrl: "", ytUrl: "" },
        { id:53,  label: "Claroscuro",                artist: "Valentina Zenere",                                                     release: "2018-04-06", season: 3, album: "Modo amar", img: "", spotifyUrl: "", ytUrl: "" },
        { id:54,  label: "Tiempo de amor",            artist: "Michael Ronda",                                                        release: "2018-04-06", season: 3, album: "Modo amar", img: "", spotifyUrl: "", ytUrl: "" },
        { id:55,  label: "Tu cárcel",                 artist: "Karol Sevilla & Michael Ronda",                                       release: "2018-04-06", season: 3, album: "Modo amar", img: "", spotifyUrl: "", ytUrl: "" },
        { id:56,  label: "Despierta mi mundo",        artist: "Karol Sevilla, Ruggero Pasquarelli, Michael Ronda, Ana Jara, Chiara Parravicini, Malena Ratner & Katja Martínez", release: "2018-04-06", season: 3, album: "Modo amar", img: "", spotifyUrl: "", ytUrl: "" },
        { id:57,  label: "Quédate",                   artist: "Karol Sevilla & Ruggero Pasquarelli",                                  release: "2018-04-06", season: 3, album: "Modo amar", img: "", spotifyUrl: "", ytUrl: "" },
        { id:58,  label: "Solos",                     artist: "Valentina Zenere & Michael Ronda",                                     release: "2018-04-06", season: 3, album: "Modo amar", img: "", spotifyUrl: "", ytUrl: "" },
        { id:59,  label: "Decirte lo que siento",     artist: "Gastón Vietto",                                                        release: "2018-04-06", season: 3, album: "Modo amar", img: "", spotifyUrl: "", ytUrl: "" },
        { id:60,  label: "Mi corazón hace wow wow",   artist: "Jandino",                                                              release: "2018-04-06", season: 3, album: "Modo amar", img: "", spotifyUrl: "", ytUrl: "" },
        { id:61,  label: "Nada me podrá parar",       artist: "Karol Sevilla",                                                        release: "2018-04-06", season: 3, album: "Modo amar", img: "", spotifyUrl: "", ytUrl: "" },
        { id:62,  label: "Si lo sueñas claro",        artist: "Cast",                                                                 release: "2018-04-06", season: 3, album: "Modo amar", img: "", spotifyUrl: "", ytUrl: "" },
        { id:63,  label: "Esta noche no paro",        artist: "Ruggero Pasquarelli",                                                  release: "2018-04-06", season: 3, album: "Modo amar", img: "", spotifyUrl: "", ytUrl: "" },
        { id:64,  label: "Creyendo en mí",            artist: "Chiara Parravicini",                                                   release: "2018-04-06", season: 3, album: "Modo amar", img: "", spotifyUrl: "", ytUrl: "" },
        { id:65,  label: "Nadie como tú",             artist: "Male Cast",                                                            release: "2018-04-06", season: 3, album: "Modo amar", img: "", spotifyUrl: "", ytUrl: "" },
        { id:66,  label: "Mano a mano",               artist: "Female Cast",                                                          release: "2018-04-06", season: 3, album: "Modo amar", img: "", spotifyUrl: "", ytUrl: "" },
        { id:67,  label: "Borrar tu mirada",          artist: "Karol Sevilla, Carolina Kopelioff, Ana Jara & Chiara Parravicini",     release: "2018-04-06", season: 3, album: "Modo amar", img: "", spotifyUrl: "", ytUrl: "" },
        { id:68,  label: "Todo puede cambiar",        artist: "Cast",                                                                 release: "2018-04-06", season: 3, album: "Modo amar", img: "", spotifyUrl: "", ytUrl: "" }
        ]
    
    }
}

