import { AlbumWithSongs } from "../classes/Album/AlbumKeys";

export const albums: AlbumWithSongs[] = [
  {
    id: 1,
    imgUrl: "https://upload.wikimedia.org/wikipedia/en/0/04/Soy_Luna_soundtrack.jpg",
    path: "/Soy_Luna (Album)",
    label: "Soy Luna (Album)",
    season: 1,
    nosongs: 12,
    release: "2016-02-26",
    songs: [
      {
        id: 1,
        label: "Alas",
        path: "/Alas",
        artist: "Karol Sevilla",
        release: "2016-02-26",
        season: 1,
        album: "Soy Luna",
        img: "https://upload.wikimedia.org/wikipedia/en/0/04/Soy_Luna_soundtrack.jpg",
        spotifyUrl: "https://open.spotify.com/track/4wWo2EHTXBQJG2PvTHyrRd",
        ytUrl: "https://www.youtube.com/watch?v=Vc99pIcimio"
      },
      {
        id: 2,
        label: "Valiente",
        path: "/Valiente",
        artist: "Michael Ronda",
        release: "2016-02-26",
        season: 1,
        album: "Soy Luna",
        img: "https://upload.wikimedia.org/wikipedia/en/0/04/Soy_Luna_soundtrack.jpg",
        spotifyUrl: "https://open.spotify.com/track/25x31n1U2nQIS9xHmDUKEF",
        ytUrl: "https://www.youtube.com/watch?v=ArWTbhgkH-A"
      },
      {
        id: 3,
        label: "Eres",
        path: "/Eres",
        artist: "Karol Sevilla & Michael Ronda",
        release: "2016-02-26",
        season: 1,
        album: "Soy Luna",
        img: "https://upload.wikimedia.org/wikipedia/en/0/04/Soy_Luna_soundtrack.jpg",
        spotifyUrl: "https://open.spotify.com/track/5Rbi2OkoVaeXKggzLH9NZG",
        ytUrl: "https://www.youtube.com/watch?v=DUBCQS4cdf4"
      },
      {
        id: 4,
        label: "Prófugos",
        path: "/Prófugos",
        artist: "Ruggero Pasquarelli & Valentina Zenere",
        release: "2016-02-26",
        season: 1,
        album: "Soy Luna",
        img: "https://upload.wikimedia.org/wikipedia/en/0/04/Soy_Luna_soundtrack.jpg",
        spotifyUrl: "https://open.spotify.com/track/22CI4H2HluhEgLO3PGOR2m",
        ytUrl: "https://www.youtube.com/watch?v=IOdTclyQHbc"
      },
      {
        id: 5,
        label: "Un destino",
        path: "/Un_destino",
        artist: "Michael Ronda, Lionel Ferro & Gastón Vietto",
        release: "2016-02-26",
        season: 1,
        album: "Soy Luna",
        img: "https://upload.wikimedia.org/wikipedia/en/0/04/Soy_Luna_soundtrack.jpg",
        spotifyUrl: "https://open.spotify.com/track/0gCuB6ekC1z8OYAy5ojR35",
        ytUrl: "https://www.youtube.com/watch?v=3LV4fH1p3Aw"
      },
      {
        id: 6,
        label: "Sobre ruedas",
        path: "/Sobre_ruedas",
        artist: "Female Cast",
        release: "2016-02-26",
        season: 1,
        album: "Soy Luna",
        img: "https://upload.wikimedia.org/wikipedia/en/0/04/Soy_Luna_soundtrack.jpg",
        spotifyUrl: "https://open.spotify.com/track/2DiLtJbVBGT8yjWVfHQyax",
        ytUrl: "https://www.youtube.com/watch?v=9j2W6Ge7-VU"
      },
      {
        id: 7,
        label: "Corazón",
        path: "/Corazón",
        artist: "Agustín Bernasconi & Malena Ratner",
        release: "2016-02-26",
        season: 1,
        album: "Soy Luna",
        img: "https://upload.wikimedia.org/wikipedia/en/0/04/Soy_Luna_soundtrack.jpg",
        spotifyUrl: "https://open.spotify.com/track/6A5shXDBOOnoizJpGHDUoh",
        ytUrl: "https://www.youtube.com/watch?v=xiS8b7SSuPk"
      },
      {
        id: 8,
        label: "Mírame a mí",
        path: "Mírame_a_mí",
        artist: "Valentina Zenere",
        release: "2016-02-26",
        season: 1,
        album: "Soy Luna",
        img: "https://upload.wikimedia.org/wikipedia/en/0/04/Soy_Luna_soundtrack.jpg",
        spotifyUrl: "https://open.spotify.com/track/0NOFUwXnBZFgHAKclrkgAF",
        ytUrl: "https://www.youtube.com/watch?v=kPX0mPb_Z_0"
      },
      {
        id: 9,
        label: "I'd Be Crazy",
        path: "/I'd_Be_Crazy",
        artist: "Male Cast",
        release: "2016-02-26",
        season: 1,
        album: "Soy Luna",
        img: "https://upload.wikimedia.org/wikipedia/en/0/04/Soy_Luna_soundtrack.jpg",
        spotifyUrl: "https://open.spotify.com/track/1oy6FvwMAXA1V7AYrJfQcO",
        ytUrl: "https://www.youtube.com/watch?v=zSAluFDVE9o"
      },
      {
        id: 10,
        label: "Siento",
        path: "/Siento",
        artist: "Ruggero Pasquarelli",
        release: "2016-02-26",
        season: 1,
        album: "Soy Luna",
        img: "https://upload.wikimedia.org/wikipedia/en/0/04/Soy_Luna_soundtrack.jpg",
        spotifyUrl: "https://open.spotify.com/track/7mi6yDxL2Fo9yafZkPCw2g",
        ytUrl: "https://www.youtube.com/watch?v=yTwljaoCQsE"
      },
      {
        id: 11,
        label: "Invisibles",
        path: "/Invisibles",
        artist: "Michael Ronda, Lionel Ferro & Gastón Vietto",
        release: "2016-02-26",
        season: 1,
        album: "Soy Luna",
        img: "https://upload.wikimedia.org/wikipedia/en/0/04/Soy_Luna_soundtrack.jpg",
        spotifyUrl: "https://open.spotify.com/track/52fTTDnsVZRde8ROjgOaic",
        ytUrl: "https://www.youtube.com/watch?v=GaNdEEjvb-E"
      },
      {
        id: 12,
        label: "Camino",
        path: "/Camino",
        artist: "Cast",
        release: "2016-02-26",
        season: 1,
        album: "Soy Luna",
        img: "https://upload.wikimedia.org/wikipedia/en/0/04/Soy_Luna_soundtrack.jpg",
        spotifyUrl: "https://open.spotify.com/track/5S043XSYNK90SyEPJ3yJjl",
        ytUrl: "https://www.youtube.com/watch?v=aUOjXqtrQL4"
      }
    ]
  },
  {
    id: 2,
    imgUrl: "https://upload.wikimedia.org/wikipedia/en/0/0b/Soy_Luna_-_M%C3%BAsica_en_ti.jpg",
    path: "/Musica_en_ti (Album)",
    label: "Música en ti (Album)",
    season: 1,
    nosongs: 13,
    release: "2016-08-26",
    songs: [
      { id: 13, path: "/Vuelo", label: "Vuelo", artist: "Cast", release: "2016-08-26", season: 1, album: "Música en ti", img: "https://upload.wikimedia.org/wikipedia/en/0/0b/Soy_Luna_-_M%C3%BAsica_en_ti.jpg", spotifyUrl: "", ytUrl: "" },
      { id: 14, path: "/Musica_en_ti", label: "Música en ti", artist: "Karol Sevilla", release: "2016-08-26", season: 1, album: "Música en ti", img: "https://upload.wikimedia.org/wikipedia/en/0/0b/Soy_Luna_-_M%C3%BAsica_en_ti.jpg", spotifyUrl: "", ytUrl: "" },
      { id: 15, path: "/A_rodar_mi_vida", label: "A rodar mi vida", artist: "Cast", release: "2016-08-26", season: 1, album: "Música en ti", img: "https://upload.wikimedia.org/wikipedia/en/0/0b/Soy_Luna_-_M%C3%BAsica_en_ti.jpg", spotifyUrl: "", ytUrl: "" },
      { id: 16, path: "/Nada_ni_nadie", label: "Nada ni nadie", artist: "Ruggero Pasquarelli", release: "2016-08-26", season: 1, album: "Música en ti", img: "https://upload.wikimedia.org/wikipedia/en/0/0b/Soy_Luna_-_M%C3%BAsica_en_ti.jpg", spotifyUrl: "", ytUrl: "" },
      { id: 17, path: "/Chicas_así", label: "Chicas así", artist: "Valentina Zenere, Malena Ratner & Katja Martínez", release: "2016-08-26", season: 1, album: "Música en ti", img: "https://upload.wikimedia.org/wikipedia/en/0/0b/Soy_Luna_-_M%C3%BAsica_en_ti.jpg", spotifyUrl: "", ytUrl: "" },
      { id: 18, path: "/Tengo_un_corazón", label: "Tengo un corazón", artist: "Carolina Kopelioff", release: "2016-08-26", season: 1, album: "Música en ti", img: "https://upload.wikimedia.org/wikipedia/en/0/0b/Soy_Luna_-_M%C3%BAsica_en_ti.jpg", spotifyUrl: "", ytUrl: "" },
      { id: 19, path: "/Qué_más_da", label: "Qué más da", artist: "Karol Sevilla & Ruggero Pasquarelli", release: "2016-08-26", season: 1, album: "Música en ti", img: "https://upload.wikimedia.org/wikipedia/en/0/0b/Soy_Luna_-_M%C3%BAsica_en_ti.jpg", spotifyUrl: "", ytUrl: "" },
      { id: 20, path: "/Sin_fronteras", label: "Sin fronteras", artist: "Karol Sevilla & Carolina Kopelioff", release: "2016-08-26", season: 1, album: "Música en ti", img: "https://upload.wikimedia.org/wikipedia/en/0/0b/Soy_Luna_-_M%C3%BAsica_en_ti.jpg", spotifyUrl: "", ytUrl: "" },
      { id: 21, path: "/Eres", label: "Eres (Radio Disney Vivo)", artist: "Karol Sevilla, Ruggero Pasquarelli & Michael Ronda", release: "2016-08-26", season: 1, album: "Música en ti", img: "https://upload.wikimedia.org/wikipedia/en/0/0b/Soy_Luna_-_M%C3%BAsica_en_ti.jpg", spotifyUrl: "", ytUrl: "" },
      { id: 22, path: "/Valiente", label: "Valiente (Radio Disney Vivo)", artist: "Karol Sevilla, Michael Ronda, Gastón Vietto & Lionel Ferro", release: "2016-08-26", season: 1, album: "Música en ti", img: "https://upload.wikimedia.org/wikipedia/en/0/0b/Soy_Luna_-_M%C3%BAsica_en_ti.jpg", spotifyUrl: "", ytUrl: "" },
      { id: 23, path: "/Alas", label: "Alas (Radio Disney Vivo)", artist: "Cast", release: "2016-08-26", season: 1, album: "Música en ti", img: "https://upload.wikimedia.org/wikipedia/en/0/0b/Soy_Luna_-_M%C3%BAsica_en_ti.jpg", spotifyUrl: "", ytUrl: "" },
      { id: 24, path: "/A_rodar_mi_vida", label: "A rodar mi vida (Acoustic)", artist: "Chiara Parravicini", release: "2016-08-26", season: 1, album: "Música en ti", img: "https://upload.wikimedia.org/wikipedia/en/0/0b/Soy_Luna_-_M%C3%BAsica_en_ti.jpg", spotifyUrl: "", ytUrl: "" }
    ]
  },
  {
    id: 3,
    imgUrl: "https://upload.wikimedia.org/wikipedia/en/4/40/La_vida_es_un_sue%C3%B1o.jpg",
    path: "/La_vida_es_un_sueño (Album)",
    label: "La vida es un sueño part 1 & 2 (Album)",
    season: 2,
    nosongs: 25,
    release: "2017-03-03",
    songs: [
      { id: 25, path: "/Siempre_juntos", label: "Siempre juntos", artist: "Karol Sevilla", release: "2017-03-03", season: 2, album: "La vida es un sueño", img: "https://upload.wikimedia.org/wikipedia/en/4/40/La_vida_es_un_sue%C3%B1o.jpg", spotifyUrl: "", ytUrl: "" },
      { id: 26, path: "/Alzo_mi_bandera", label: "Alzo mi bandera", artist: "Michael Ronda, Gastón Vietto & Lionel Ferro", release: "2017-03-03", season: 2, album: "La vida es un sueño", img: "https://upload.wikimedia.org/wikipedia/en/4/40/La_vida_es_un_sue%C3%B1o.jpg", spotifyUrl: "", ytUrl: "" },
      { id: 27, path: "/La_vida_es_un_sueño", label: "La vida es un sueño", artist: "Karol Sevilla", release: "2017-03-03", season: 2, album: "La vida es un sueño", img: "https://upload.wikimedia.org/wikipedia/en/4/40/La_vida_es_un_sue%C3%B1o.jpg", spotifyUrl: "", ytUrl: "" },
      { id: 28, path: "/Fush,_¡Te_vas", label: "Fush, ¡Te vas!", artist: "Katja Martínez", release: "2017-03-03", season: 2, album: "La vida es un sueño", img: "https://upload.wikimedia.org/wikipedia/en/4/40/La_vida_es_un_sue%C3%B1o.jpg", spotifyUrl: "", ytUrl: "" },
      { id: 29, path: "/¿Cómo_me_ves?", label: "¿Cómo me ves?", artist: "Valentina Zenere", release: "2017-03-03", season: 2, album: "La vida es un sueño", img: "https://upload.wikimedia.org/wikipedia/en/4/40/La_vida_es_un_sue%C3%B1o.jpg", spotifyUrl: "", ytUrl: "" },
      { id: 30, path: "/Mitad_y_mitad", label: "Mitad y mitad", artist: "Agustín Bernasconi & Carolina Kopelioff", release: "2017-03-03", season: 2, album: "La vida es un sueño", img: "https://upload.wikimedia.org/wikipedia/en/4/40/La_vida_es_un_sue%C3%B1o.jpg", spotifyUrl: "", ytUrl: "" },
      { id: 31, path: "/Valiente", label: "Valiente", artist: "Cast", release: "2017-03-03", season: 2, album: "La vida es un sueño", img: "https://upload.wikimedia.org/wikipedia/en/4/40/La_vida_es_un_sue%C3%B1o.jpg", spotifyUrl: "", ytUrl: "" },
      { id: 32, path: "/Honey_Funny", label: "Honey Funny", artist: "Chiara Parravicini, Ana Jara & Jorge López", release: "2017-03-03", season: 2, album: "La vida es un sueño", img: "https://upload.wikimedia.org/wikipedia/en/4/40/La_vida_es_un_sue%C3%B1o.jpg", spotifyUrl: "", ytUrl: "" },
      { id: 33, path: "/Linda", label: "Linda", artist: "Michael Ronda, Gastón Vietto & Lionel Ferro", release: "2017-03-03", season: 2, album: "La vida es un sueño", img: "https://upload.wikimedia.org/wikipedia/en/4/40/La_vida_es_un_sue%C3%B1o.jpg", spotifyUrl: "", ytUrl: "" },
      { id: 34, path: "/Cuenta_conmigo", label: "Cuenta conmigo", artist: "Cast", release: "2017-03-03", season: 2, album: "La vida es un sueño", img: "https://upload.wikimedia.org/wikipedia/en/4/40/La_vida_es_un_sue%C3%B1o.jpg", spotifyUrl: "", ytUrl: "" },
      { id: 35, path: "/Vives_en_mí", label: "Vives en mí", artist: "Karol Sevilla & Ruggero Pasquarelli", release: "2017-03-03", season: 2, album: "La vida es un sueño", img: "https://upload.wikimedia.org/wikipedia/en/4/40/La_vida_es_un_sue%C3%B1o.jpg", spotifyUrl: "", ytUrl: "" },
      { id: 36, path: "/I've_Got_a_Feeling", label: "I've Got a Feeling", artist: "Cast", release: "2017-03-03", season: 2, album: "La vida es un sueño", img: "https://upload.wikimedia.org/wikipedia/en/4/40/La_vida_es_un_sue%C3%B1o.jpg", spotifyUrl: "", ytUrl: "" },
      { id: 37, path: "/Princesa", label: "Princesa", artist: "Ruggero Pasquarelli", release: "2017-03-03", season: 2, album: "La vida es un sueño", img: "https://upload.wikimedia.org/wikipedia/en/4/40/La_vida_es_un_sue%C3%B1o.jpg", spotifyUrl: "", ytUrl: "" },
      { id: 38, path: "/Footloose", label: "Footloose", artist: "Cast", release: "2017-03-03", season: 2, album: "La vida es un sueño", img: "https://upload.wikimedia.org/wikipedia/en/4/40/La_vida_es_un_sue%C3%B1o.jpg", spotifyUrl: "", ytUrl: "" },
      { id: 39, path: "/Sólo_para_ti", label: "Sólo para ti", artist: "Karol Sevilla", release: "2017-03-03", season: 2, album: "La vida es un sueño", img: "https://upload.wikimedia.org/wikipedia/en/4/40/La_vida_es_un_sue%C3%B1o.jpg", spotifyUrl: "", ytUrl: "" },
      { id: 40, path: "/Catch_Me_If_You_Can", label: "Catch Me If You Can", artist: "Valentina Zenere", release: "2017-03-03", season: 2, album: "La vida es un sueño", img: "https://upload.wikimedia.org/wikipedia/en/4/40/La_vida_es_un_sue%C3%B1o.jpg", spotifyUrl: "", ytUrl: "" },
      { id: 41, path: "/Pienso", label: "Pienso", artist: "Michael Ronda, Gastón Vietto & Lionel Ferro", release: "2017-03-03", season: 2, album: "La vida es un sueño", img: "https://upload.wikimedia.org/wikipedia/en/4/40/La_vida_es_un_sue%C3%B1o.jpg", spotifyUrl: "", ytUrl: "" },
      { id: 42, path: "/Andaremos", label: "Andaremos", artist: "Karol Sevilla & Michael Ronda", release: "2017-03-03", season: 2, album: "La vida es un sueño", img: "https://upload.wikimedia.org/wikipedia/en/4/40/La_vida_es_un_sue%C3%B1o.jpg", spotifyUrl: "", ytUrl: "" },
      { id: 43, path: "/Allá_voy", label: "Allá voy", artist: "Ruggero Pasquarelli", release: "2017-03-03", season: 2, album: "La vida es un sueño", img: "https://upload.wikimedia.org/wikipedia/en/4/40/La_vida_es_un_sue%C3%B1o.jpg", spotifyUrl: "", ytUrl: "" },
      { id: 44, path: "/No_te_pido_mucho", label: "No te pido mucho", artist: "Karol Sevilla", release: "2017-03-03", season: 2, album: "La vida es un sueño", img: "https://upload.wikimedia.org/wikipedia/en/4/40/La_vida_es_un_sue%C3%B1o.jpg", spotifyUrl: "", ytUrl: "" },
      { id: 45, path: "/Stranger", label: "Stranger", artist: "Ruggero Pasquarelli", release: "2017-03-03", season: 2, album: "La vida es un sueño", img: "https://upload.wikimedia.org/wikipedia/en/4/40/La_vida_es_un_sue%C3%B1o.jpg", spotifyUrl: "", ytUrl: "" },
      { id: 46, path: "/Aquí_estoy", label: "Aquí estoy", artist: "Agustín Bernasconi & Ruggero Pasquarelli", release: "2017-03-03", season: 2, album: "La vida es un sueño", img: "https://upload.wikimedia.org/wikipedia/en/4/40/La_vida_es_un_sue%C3%B1o.jpg", spotifyUrl: "", ytUrl: "" },
      { id: 47, path: "/Yes,_I_Do", label: "Yes, I Do", artist: "Chiara Parravicini", release: "2017-03-03", season: 2, album: "La vida es un sueño", img: "https://upload.wikimedia.org/wikipedia/en/4/40/La_vida_es_un_sue%C3%B1o.jpg", spotifyUrl: "", ytUrl: "" },
      { id: 48, path: "/Yo_quisiera", label: "Yo quisiera", artist: "Michael Ronda", release: "2017-03-03", season: 2, album: "La vida es un sueño", img: "https://upload.wikimedia.org/wikipedia/en/4/40/La_vida_es_un_sue%C3%B1o.jpg", spotifyUrl: "", ytUrl: "" },
      { id: 49, path: "/Siempre_juntos", label: "Siempre juntos (group version)", artist: "Cast", release: "2017-03-03", season: 2, album: "La vida es un sueño", img: "https://upload.wikimedia.org/wikipedia/en/4/40/La_vida_es_un_sue%C3%B1o.jpg", spotifyUrl: "", ytUrl: "" }
    ]
  },
  {
    id: 4,
    imgUrl: "https://i.scdn.co/image/ab67616d0000b273effbb11a16be922e05017e98",
    path: "/Modo_Amar (Album)",
    label: "Modo Amar (Album)",
    season: 3,
    nosongs: 19,
    release: "2018-04-06",
    songs: [
      { id: 50, path: "/Modo_amar", label: "Modo amar", artist: "Cast", release: "2018-04-06", season: 3, album: "Modo Amar", img: "https://i.scdn.co/image/ab67616d0000b273effbb11a16be922e05017e98", spotifyUrl: "", ytUrl: "" },
      { id: 51, path: "/Soy_yo", label: "Soy yo", artist: "Karol Sevilla", release: "2018-04-06", season: 3, album: "Modo Amar", img: "https://i.scdn.co/image/ab67616d0000b273effbb11a16be922e05017e98", spotifyUrl: "", ytUrl: "" },
      { id: 52, path: "/Quiero_verte_sonreir", label: "Quiero verte sonreir", artist: "Ruggero Pasquarelli", release: "2018-04-06", season: 3, album: "Modo Amar", img: "https://i.scdn.co/image/ab67616d0000b273effbb11a16be922e05017e98", spotifyUrl: "", ytUrl: "" },
      { id: 53, path: "/Claroscuro", label: "Claroscuro", artist: "Valentina Zenere", release: "2018-04-06", season: 3, album: "Modo Amar", img: "https://i.scdn.co/image/ab67616d0000b273effbb11a16be922e05017e98", spotifyUrl: "", ytUrl: "" },
      { id: 54, path: "/Tiempo_de_amor", label: "Tiempo de amor", artist: "Michael Ronda", release: "2018-04-06", season: 3, album: "Modo Amar", img: "https://i.scdn.co/image/ab67616d0000b273effbb11a16be922e05017e98", spotifyUrl: "", ytUrl: "" },
      { id: 55, path: "/Tu_cárcel", label: "Tu cárcel", artist: "Karol Sevilla & Michael Ronda", release: "2018-04-06", season: 3, album: "Modo Amar", img: "https://i.scdn.co/image/ab67616d0000b273effbb11a16be922e05017e98", spotifyUrl: "", ytUrl: "" },
      { id: 56, path: "/Despierta_mi_mundo", label: "Despierta mi mundo", artist: "Karol Sevilla, Ruggero Pasquarelli, Michael Ronda, Ana Jara, Chiara Parravicini, Malena Ratner & Katja Martínez", release: "2018-04-06", season: 3, album: "Modo Amar", img: "https://i.scdn.co/image/ab67616d0000b273effbb11a16be922e05017e98", spotifyUrl: "", ytUrl: "" },
      { id: 57, path: "/Quédate", label: "Quédate", artist: "Karol Sevilla & Ruggero Pasquarelli", release: "2018-04-06", season: 3, album: "Modo Amar", img: "https://i.scdn.co/image/ab67616d0000b273effbb11a16be922e05017e98", spotifyUrl: "", ytUrl: "" },
      { id: 58, path: "/Solos", label: "Solos", artist: "Valentina Zenere & Michael Ronda", release: "2018-04-06", season: 3, album: "Modo Amar", img: "https://i.scdn.co/image/ab67616d0000b273effbb11a16be922e05017e98", spotifyUrl: "", ytUrl: "" },
      { id: 59, path: "/Decirte_lo_que_siento", label: "Decirte lo que siento", artist: "Gastón Vietto", release: "2018-04-06", season: 3, album: "Modo Amar", img: "https://i.scdn.co/image/ab67616d0000b273effbb11a16be922e05017e98", spotifyUrl: "", ytUrl: "" },
      { id: 60, path: "/Mi_corazón_hace_wow_wow", label: "Mi corazón hace wow wow", artist: "Jandino", release: "2018-04-06", season: 3, album: "Modo Amar", img: "https://i.scdn.co/image/ab67616d0000b273effbb11a16be922e05017e98", spotifyUrl: "", ytUrl: "" },
      { id: 61, path: "/Nada_me_podrá_parar", label: "Nada me podrá parar", artist: "Karol Sevilla", release: "2018-04-06", season: 3, album: "Modo Amar", img: "https://i.scdn.co/image/ab67616d0000b273effbb11a16be922e05017e98", spotifyUrl: "", ytUrl: "" },
      { id: 62, path: "/Si_lo_sueñas_claro", label: "Si lo sueñas claro", artist: "Cast", release: "2018-04-06", season: 3, album: "Modo Amar", img: "https://i.scdn.co/image/ab67616d0000b273effbb11a16be922e05017e98", spotifyUrl: "", ytUrl: "" },
      { id: 63, path: "/Esta_noche_no_paro", label: "Esta noche no paro", artist: "Ruggero Pasquarelli", release: "2018-04-06", season: 3, album: "Modo Amar", img: "https://i.scdn.co/image/ab67616d0000b273effbb11a16be922e05017e98", spotifyUrl: "", ytUrl: "" },
      { id: 64, path: "/Creyendo_en_mí", label: "Creyendo en mí", artist: "Chiara Parravicini", release: "2018-04-06", season: 3, album: "Modo Amar", img: "https://i.scdn.co/image/ab67616d0000b273effbb11a16be922e05017e98", spotifyUrl: "", ytUrl: "" },
      { id: 65, path: "/Nadie_somo_tú", label: "Nadie somo tú", artist: "Male Cast", release: "2018-04-06", season: 3, album: "Modo Amar", img: "https://i.scdn.co/image/ab67616d0000b273effbb11a16be922e05017e98", spotifyUrl: "", ytUrl: "" },
      { id: 66, path: "/Mano_a_mano", label: "Mano a mano", artist: "Female Cast", release: "2018-04-06", season: 3, album: "Modo Amar", img: "https://i.scdn.co/image/ab67616d0000b273effbb11a16be922e05017e98", spotifyUrl: "", ytUrl: "" },
      { id: 67, path: "/Borrar tu mirada", label: "Borrar tu mirada", artist: "Karol Sevilla, Carolina Kopelioff, Ana Jara & Chiara Parravicini", release: "2018-04-06", season: 3, album: "Modo Amar", img: "https://i.scdn.co/image/ab67616d0000b273effbb11a16be922e05017e98", spotifyUrl: "", ytUrl: "" },
      { id: 68, path: "/Todo puede cambiar", label: "Todo puede cambiar", artist: "Cast", release: "2018-04-06", season: 3, album: "Modo Amar", img: "https://i.scdn.co/image/ab67616d0000b273effbb11a16be922e05017e98", spotifyUrl: "", ytUrl: "" }
    ]
  }
];
