import { Page } from "../classes/AllType";

export const characters1: Page[] = [
    {
        id: "1", 
        label: "Luna", 
        imgUrl: "https://i.pinimg.com/564x/c1/58/41/c158415ece8282618e58a525e51592d9.jpg",  
        actor: "Karol Sevilla", 
        path: "/Luna", 
        description: "Luna is a sweet, cheerful and big-hearted girl from Mexico. She is optimistic, loyal to her friends and family, and incredibly determined: once she sets herself a goal, she works hard until she reaches it.",    
    },
    {
        id: "2", 
        label: "Matteo", 
        imgUrl: "https://i.pinimg.com/736x/6a/aa/f1/6aaaf1adbf0e841fa0257a352db1d031.jpg", 
        actor: "Ruggero Pasquarelli", 
        path: "/Matteo",
        description: "Matteo starts out as a very presumptuous, vain and seemingly superficial boy, proud of being the 'King of the Track'. Behind the arrogance, he is intelligent, passionate about skating and music, and he gradually shows a genuinely caring and protective side, especially with Luna.",

    },
    {
        id: "3", 
        label: "Simón",
        imgUrl:  "https://pbs.twimg.com/profile_images/782192147793674244/I0H9Ia9N_400x400.jpg", 
        actor: "Micheal Ronda", 
        path: "/Simón",
        description: "Simón is funny, warm and deeply caring. He loves music and skating, is humble and encouraging, and is always ready to support his friends. He often puts other people’s happiness before his own, especially when it comes to Luna.",

    },
]

export const characters2: Page[] = [
    {
      id: "4", 
      label: "Ámbar", 
      imgUrl: "https://i.pinimg.com/564x/f3/46/bb/f346bb7dd9e331554633f7cc15e72d59.jpg", 
      actor: "Valentina Zenere", 
      path: "/Ámbar",
      description: "Ámbar is initially superficial, spoiled and very competitive. She craves attention, wants to be the best at everything and uses manipulation to get what she wants. Underneath her schemes she is insecure and jealous, especially of Luna’s loving family, and over time her more vulnerable and conflicted side appears.",
    },
    {
      id: "5", 
      label: "Nina", 
      imgUrl: "https://i.pinimg.com/564x/88/72/a2/8872a20dd293eb403e2efb6206e90566.jpg", 
      actor: "Carolina Kopelioff", 
      path: "/Nina",
      description: "Nina is highly intelligent, curious and a bit of a bookworm. She is shy, introverted and insecure at first, often hiding behind her anonymous online persona, but she is also kind, thoughtful and idealistic, slowly learning to believe in herself.",
    },
    {
      id: "6", 
      label: "Delfi", 
      imgUrl: "https://i.pinimg.com/736x/ca/53/81/ca538152c9e81be9046ee9b6a3a9eeed.jpg", 
      actor: "Malena Ratner", 
      path: "/Delfi",
      description: "Delfi starts out as a vain, judgmental and gossip-loving girl who follows Ámbar’s lead and cares a lot about image and social media. Underneath she is sensitive, loyal and capable of real kindness, and as she grows, she becomes more independent, empathetic and emotionally mature.", 
    },
    {
      id: "7", 
      label: "Gastón", 
      imgUrl:"https://img.wattpad.com/3e291a72d660402803cef7dccd883b845d5aeff4/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f776174747061642d6d656469612d736572766963652f53746f7279496d6167652f384a6372654d706e5f555f4c70513d3d2d3431323030313537342e313462653835326238316538616233633830333035303130383930332e6a7067?s=fit&w=720&h=720", 
      actor: "Agustìn Bernasconi", 
      path: "/Gastón",
      description:"Gastón is popular, charming and confident, but also respectful, rational and more grounded than Matteo. He loves music and books, especially science fiction, and often acts as the voice of reason, even while struggling with his own feelings and expectations.", 
    },
    {
      id: "8", 
      label: "Jazmín", 
      imgUrl:"https://i.pinimg.com/474x/d5/f1/5b/d5f15bdcf97948598c92526fce7bf739.jpg", 
      actor: "Katja Martínez", 
      path: "/Jazmín",
      description:"Jazmín is energetic, dramatic and very talkative, with absolutely no filter. She is obsessed with trends and online fame, often naïve and clueless about what is really going on around her, but she is also affectionate, loyal and capable of real growth when she learns to think for herself.",
    },
    {
      id: "8", 
      label: "Jim", 
      imgUrl: "https://i.pinimg.com/564x/d1/fb/f9/d1fbf97052e502657c3d99a9c4f854f7.jpg", 
      actor: "Ana Jara", 
      path: "/Jim",
      description: "Jim is creative, impulsive and full of ideas. She is sweet, friendly and very expressive, with a huge passion for dance and choreography. Together with Yam she is bold and adventurous, even if her impulsiveness sometimes gets her into trouble.",
    },
    {
      id: "9", 
      label: "Yam", 
      imgUrl: "https://i.pinimg.com/474x/99/20/4a/99204a7ddc1e80b9289d460df7046a14.jpg", 
      actor: "Chiara Parravicini", 
      path: "/Yam",
      description: "Yam is emotional, romantic and very passionate about music and fashion. She can be insecure and jealous, but she is loyal, hard-working and caring with the people she loves, especially Jim and Ramiro. She grows a lot in self-confidence over the series.",
    },
    {
      id: "10",
      label: "Ramiro", 
      imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRjUIZ2hYuSBkVMxmSRHNKOx4WkG1cXGJek5g&s", 
      actor: "Jorge López", 
      path: "/Ramiro",
      description: "Ramiro is proud, ambitious and easily frustrated when things don’t go his way. He can come across as arrogant and selfish, but behind that he is disciplined and passionate about dance and skating, and he gradually learns to accept his mistakes and show his softer side.",
    },
    {
      id: "11",
      label: "Pedro", 
      imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTb3mT6g6di-cZYgxGWAAdXiM4XNYEF67FLNmZ5vcpLjht0h5PgU9ELCsNPnGWKOb4rBn8&usqp=CAU", 
      actor:"Gastón Vietto", 
      path: "/Pedro",
      description: "Pedro is good-natured, loyal and slightly awkward, with a big heart. He works hard, loves music and drumming, and is deeply supportive of his friends. He often downplays his own feelings, especially when it comes to love, in order to not hurt anyone.",
    },
    {
      id: "13",
      label: "Nico", 
      imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTHwqrTXcJ8cN3hc4kbzx1tfn5H5sDjtj3NyJPHj5mu5oSWCiRYqQNvJ4s23dPq2hojV94&usqp=CAU", 
      actor: "Lionel Ferro", 
      path: "/Nico",
      description: "Nico is warm, friendly and easy-going, the kind of guy people feel comfortable with right away. He is supportive, fun and a bit goofy, dreams about making music with Pedro, and often acts as a calm, positive presence in the group.",
    },
    {
      id: "14",
      label: "Tamara", 
      imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTA9VssqUHjDcsImv5kA7TG8ir_3BXcC8QB-A&s", 
      actor: "Luz Capriota", 
      path: "/Tamara",
      description: "Tamara is responsible, strict and highly organized, but also fair and caring. As the manager of Jam & Roller she demands discipline and professionalism, yet she genuinely believes in the kids’ talent and acts like a mentor and protective older sister.", 
    },
    {
      id: "15",
      label: "Mrs. Benson", 
      imgUrl: "https://pbs.twimg.com/profile_images/896031069849497601/mFX48SWF_400x400.jpg",  
      actor:"Lucila Gandolfo", 
      path: "/Sharon",
      description: "Sharon is elegant, cold and calculating. She is a sophisticated businesswoman who is obsessed with control and appearances, willing to lie and manipulate to protect her fortune and her version of the past. Her cruelty often hides deep guilt, fear and denial.",
    },
    {
      id: "16",
      label: "Rey", 
      imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQeTnM8jeVkNkCO0yXhd6dwZYQ1O-fZYq8Idg&s", 
      actor: "Rodrigo Pedreira", 
      path: "/Rey",
      description: "Rey is serious, meticulous and extremely loyal to Sharon. He usually shows a stiff, formal and almost emotionless exterior, but he is also anxious and conflicted when their schemes go too far. Over time, his conscience starts to clash with his loyalty.",
    },
    {
      id: "17",
      label: "Miguel", 
      imgUrl: "https://tiermaker.com/images/chart/chart/soy-luna-characters-520944/migueljpg.png", 
      actor: "David Muri", 
      path: "/Miguel",
      description: "Miguel is kind, honest and hard-working. He is a devoted father and husband, protective of Luna and always trying to do what is best for his family, even when that means making sacrifices or enduring Sharon’s authority.",
    },
    {
      id: "18",
      label: "Mónica", 
      imgUrl: "https://assets.puzzlefactory.com/puzzle/352/239/original.jpg", 
      actor: "Ana Carolina Valsagna", 
      path: "/Mónica",
      description: "Mónica is warm, maternal and supportive. She worries a lot and is often emotional, but she is brave when it comes to defending Luna. She acts as an anchor and emotional support for both Luna and Miguel.",
    },
    {
      id: "19",
      label: "Tino", 
      imgUrl: "src/assets/Tino.jpg", 
      actor: "Diego Sassi Alcalá", 
      path: "/Tino", 
      description: "Tino is clumsy, goofy and comedic. He is well-meaning but not very bright, often messing things up in a funny way. Despite his silliness, he is loyal and affectionate towards his friends, especially Cato and the Valente family.",
},
    {
      id: "20",
      label: "Cato", 
      imgUrl: "src/assets/Cato.jpg", 
      actor: "Germán Tripel", 
      path: "/Cato",
      description: "Cato is also a comic character, anxious and a bit neurotic compared to Tino. He worries about rules and getting into trouble, but goes along with schemes anyway. He is kind-hearted and, in his own odd way, very loyal and caring.",
    },
    {
      id: "21",
      label: "Amanda", 
      imgUrl: "src/assets/Amanda.jpg", 
      actor: "Antonella Querzoli", 
      path: "/Amanda",
      description: "Amanda often appears cold, strict and distant, but behind that façade she is deeply caring and protective. She is kind to Luna and the Valente family, takes her work seriously and is always willing to help the people she loves, even if she doesn’t always show her feelings openly.", 
    },
    {
      id: "22",
      label: "Ricardo", 
      imgUrl: "src/assets/ricardo.jpg", 
      actor: "Ezequiel Rodríquez", 
      path: "/Ricardo", 
      description: "Ricardo is creative, absent-minded and somewhat immature at times, but he has a good heart. As Nina’s father he is loving yet clumsy, often not realizing how his choices affect her. Over time he grows more responsible and emotionally open.",
    },
    {
      id: "23",
      label: "Ana", 
      imgUrl: "src/assets/ana.jpg", 
      actor: "Caro Ibarro", 
      path: "/Ana",
      description: "Ana is intelligent, strong-willed and professional. She can seem strict or distant, but she cares deeply about Nina and struggles with guilt over past decisions. She learns to communicate better and to balance work with her role as a mother.",

    },
    {
      id: "24",
      label: "Mora",
      imgUrl:  "src/assets/mora.jpg", 
      actor: "Paula Kohan", 
      path: "/Mora",
      description: "Mora is stylish, confident and creative, with a strong sense of aesthetics. She is initially self-focused and a bit dramatic, but she is also supportive and protective, especially toward Ana, Nina and the Jam & Roller kids.",

    },
    {
      id: "25",
      label: "Juliana", 
      imgUrl: "src/assets/juliana.jpg", 
      actor:"Estela Ribeiro", 
      path: "/Juliana",
      description: "Juliana, known as Marisa Mint, is disciplined, demanding and highly perfectionistic. She is tough on her students and hides her emotions behind a strict professional façade, but deep down she is passionate about skating and wants to help them reach their full potential.",
    },
    {
      id: "26",
      label: "Alfredo", 
      imgUrl: "src/assets/alfredo.jpg", 
      actor:"Roberto Carnaghi", 
      path: "/Alfredo",
      description: "Alfredo is gentle, wise and somewhat melancholic. As the elder of the family he regrets past mistakes and wants to repair the damage done. He is affectionate with Luna and tries to guide others toward truth and reconciliation.",
    },
    {
      id: "27",
      label: "Gary", 
      imgUrl: "https://vignette.wikia.nocookie.net/soyluna/images/b/bd/Gary.jpg/revision/latest?cb=20200625095218", 
      actor: "Joaquín Berthold", 
      path: "/Gary",
      description: "Gary is ambitious, controlling and opportunistic. He focuses on profit and image more than on people’s feelings, and he has no problem using pressure or manipulation to get what he wants from the skaters and the rink.",
    },
    {
      id: "28",
      label: "Benicio", 
      imgUrl: "src/assets/benicio.jpg", 
      actor: "Pasquale Di Nuzzo", 
      path: "/Benicio",
      description: "Benicio is arrogant, competitive and manipulative. He enjoys provoking others and uses his charm in a self-serving way. Even so, his jealousy and insecurity are often what push him into schemes and bad decisions.",
    },
    {
      id: "29",
      label: "Emilia", 
      imgUrl: "https://i.pinimg.com/736x/a6/ea/20/a6ea2069ff3aef1a27e5f6c098d7ba97.jpg", 
      actor: "Giovanna Reynaud", 
      path: "/Emila",
      description:     "Emilia is confident, ambitious and highly competitive. She often comes across as arrogant and sharp-tongued, especially when she feels her spotlight is threatened. Behind her tough and glamorous exterior, she is deeply insecure and vulnerable, craving recognition and genuine affection. Over time she reveals a more sensitive and loyal side, especially in her relationship with Benicio and when she finally allows herself to be honest about her feelings.",
    },
    {
      id: "30",
      label: "Eric", 
      imgUrl: "src/assets/eric.jpg", 
      actor: "Jandino", 
      path: "/Eric",
      description:"Eric is kind, a bit shy and slightly awkward, especially when it comes to his crush on Nina. He genuinely wants to help and do a good job at the rink, but often finds himself overwhelmed by Gary’s pressure and the complicated dynamics around him rather than creating drama himself.",
    },
    {
      id: "31",
      label: "Maggie", 
      imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRitLGbjcYLFLEPC3W2dUF_AUMIFrXS13c0jg&s", 
      actor: "Victoria Suárez Battán", 
      path:"/Maggie",
      description: "Maggie starts as a sneaky, ambitious spy for Sharon and Rey, using her charm to get information. Underneath, she is insecure and longs for genuine affection. Her relationship with Rey brings out both her manipulative and her vulnerable sides.",
    }
]
