import { Page } from "../classes/AllType";
import { GastinaImg, JicoImg, LumonImg, LutteoImg, MambarImg, PelfiImg, SimbarImg, YamiroImg, GasteoImg, JimYamImg,  LuninaImg, SimonPedroNicoImg, SitteoImg, ÁmbarDelfiJazmínImg, ÁmbiliaImg, TinoCatoImg, AnaMoraImg } from "./Images"

export const searchResults: Page[] = [
    {
      id: "1", 
      category: "Characters", 
      label: "Luna", 
      imgUrl: "https://i.pinimg.com/564x/c1/58/41/c158415ece8282618e58a525e51592d9.jpg",  
      actor: "Karol Sevilla", 
      path:"/Characters/Luna",
    },{
      id: "2", 
      category: "Characters", 
      label: "Matteo", 
      imgUrl: "https://i.pinimg.com/736x/6a/aa/f1/6aaaf1adbf0e841fa0257a352db1d031.jpg", 
      actor: "Ruggero Pasquarelli", 
      path: "/Characters/Matteo"},
    {
      id: "3", 
      category: "Characters", 
      label: "Simón",
      imgUrl:  "https://pbs.twimg.com/profile_images/782192147793674244/I0H9Ia9N_400x400.jpg", 
      actor: "Micheal Ronda", 
      path: "/Characters/Simón"},
    {
      id: "4", 
      category: "Characters", 
      label: "Ámbar", 
      imgUrl: "https://i.pinimg.com/564x/f3/46/bb/f346bb7dd9e331554633f7cc15e72d59.jpg", 
      actor: "Valentina Zenere", 
      path: "/Characters/Ámbar"},
    {
      id: "5", 
      category: "Characters", 
      label: "Nina", 
      imgUrl: "https://i.pinimg.com/564x/88/72/a2/8872a20dd293eb403e2efb6206e90566.jpg", 
      actor: "Carolina Kopelioff", 
      path: "/Characters/Nina"},
    {
      id: "6", 
      category: "Characters", 
      label: "Delfi", 
      imgUrl: "https://i.pinimg.com/736x/ca/53/81/ca538152c9e81be9046ee9b6a3a9eeed.jpg", 
      actor: "Malena Ratner", 
      path: "/Characters/Delfi"},
    {
      id: "7", 
      category: "Characters", 
      label: "Gastón", 
      imgUrl:"https://img.wattpad.com/3e291a72d660402803cef7dccd883b845d5aeff4/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f776174747061642d6d656469612d736572766963652f53746f7279496d6167652f384a6372654d706e5f555f4c70513d3d2d3431323030313537342e313462653835326238316538616233633830333035303130383930332e6a7067?s=fit&w=720&h=720", 
      actor: "Agustìn Bernasconi", 
      path: "/Characters/Gastón"},
    {
      id: "8", 
      category: "Characters", 
      label: "Jazmín", 
      imgUrl:"https://i.pinimg.com/474x/d5/f1/5b/d5f15bdcf97948598c92526fce7bf739.jpg", 
      actor: "Katja Martínez", 
      path: "/Characters/Jazmín"},
    {
      id: "8", 
      category: "Characters", 
      label: "Jim", 
      imgUrl: "https://i.pinimg.com/564x/d1/fb/f9/d1fbf97052e502657c3d99a9c4f854f7.jpg", 
      actor: "Ana Jara", 
      path: "/Characters/Jim"
    },
    {
      id: "9", 
      category: "Characters", 
      label: "Yam", 
      imgUrl: "https://i.pinimg.com/474x/99/20/4a/99204a7ddc1e80b9289d460df7046a14.jpg", 
      actor: "Chiara Parravicini", 
      path: "/Characters/Yam"},
    {
      id: "10",
      category: "Characters", 
      label:  "Ramiro", 
      imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRjUIZ2hYuSBkVMxmSRHNKOx4WkG1cXGJek5g&s", 
      actor: "Jorge López", 
      path: "/Characters/Ramiro"
    },
    {
      id: "11",
      category: "Characters", 
      label:  "Pedro", 
      imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTb3mT6g6di-cZYgxGWAAdXiM4XNYEF67FLNmZ5vcpLjht0h5PgU9ELCsNPnGWKOb4rBn8&usqp=CAU", 
      actor:"Gastón Vietto", 
      path: "/Characters/Pedro"},
    {
      id: "13",
      category: "Characters", 
      label:  "Nico", 
      imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTHwqrTXcJ8cN3hc4kbzx1tfn5H5sDjtj3NyJPHj5mu5oSWCiRYqQNvJ4s23dPq2hojV94&usqp=CAU", 
      actor: "Lionel Ferro", 
      path: "/Characters/Nico"},
    {
      id: "14",
      category: "Characters", 
      label:  "Tamara", 
      imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTA9VssqUHjDcsImv5kA7TG8ir_3BXcC8QB-A&s", 
      actor: "Luz Capriota", 
      path: "/Characters/Tamara"
    },
    {
      id: "15",
      category: "Characters", 
      label:  "Mrs. Benson", 
      imgUrl: "https://pbs.twimg.com/profile_images/896031069849497601/mFX48SWF_400x400.jpg",  
      actor:"Lucila Gandolfo", 
      path: "/Characters/Sharon"
    },
    {
      id: "16",
      category: "Characters", 
      label: "Rey", 
      imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQeTnM8jeVkNkCO0yXhd6dwZYQ1O-fZYq8Idg&s", 
      actor: "Rodrigo Pedreira", 
      path: "/Characters/Rey"
    },
    {
      id: "17",
      category: "Characters", 
      label:  "Miguel", 
      imgUrl: "https://tiermaker.com/images/chart/chart/soy-luna-characters-520944/migueljpg.png", 
      actor: "David Muri", 
      path: "/Characters/Miguel"},
    {
      id: "18",
      category: "Characters", 
      label:  "Mónica", 
      imgUrl: "https://assets.puzzlefactory.com/puzzle/352/239/original.jpg", 
      actor: "Ana Carolina Valsagna", 
      path: "/Characters/Mónica"},
    {
      id: "19",
      category: "Characters", 
      label:  "Tino", 
      imgUrl: "src/assets/Tino.jpg", 
      actor: "Diego Sassi Alcalá", 
      path: "/Characters/Tino"},
    {
      id: "20",
      category: "Characters", 
      label:  "Cato", 
      imgUrl: "src/assets/Cato.jpg", 
      actor: "Germán Tripel", 
      path: "/Characters/Cato"},
    {
      id: "21",
      category: "Characters", 
      label:  "Amanda", 
      imgUrl: "src/assets/Amanda.jpg", 
      actor: "Antonella Querzoli", 
      path: "/Characters/Amanda"},
    {
      id: "22",
      category: "Characters", 
      label:  "Ricardo", 
      imgUrl: "src/assets/ricardo.jpg", 
      actor: "Ezequiel Rodríquez", 
      path: "/Characters/Ricardo"},
    {
      id: "23",
      category: "Characters", 
      label:  "Ana", 
      imgUrl: "src/assets/ana.jpg", 
      actor: "Caro Ibarro", 
      path: "/Characters/Ana"},
    {
      id: "24",
      category: "Characters", 
      label:  "Mora", 
      imgUrl:  "src/assets/mora.jpg", 
      actor: "Paula Kohan", 
      path: "/Characters/Mora"},
    {
      id: "25",
      category: "Characters", 
      label:  "Juliana", 
      imgUrl: "src/assets/juliana.jpg", 
      actor:"Estela Ribeiro", 
      path: "/Characters/Juliana"},
    {
      id: "26",
      category: "Characters", 
      label:  "Alfredo", 
      imgUrl: "src/assets/alfredo.jpg", 
      actor:"Roberto Carnaghi", 
      path: "/Characters/Alfredo"},
    {
      id: "27",
      category: "Characters", 
      label:  "Gary", 
      imgUrl: "https://vignette.wikia.nocookie.net/soyluna/images/b/bd/Gary.jpg/revision/latest?cb=20200625095218", 
      actor: "Joaquín Berthold", 
      path: "/Characters/Gary"},
    {
      id: "28",
      category: "Characters", 
      label:  "Benicio", 
      imgUrl: "src/assets/benicio.jpg", 
      actor: "Pasquale Di Nuzzo", 
      path: "/Benicio"
    },
    {
      id: "29",
      category: "Characters", 
      label:  "Emilia", 
      imgUrl: "https://i.pinimg.com/736x/a6/ea/20/a6ea2069ff3aef1a27e5f6c098d7ba97.jpg", 
      actor: "Giovanna Reynaud", 
      path: "/Characters/Emila"
    },
    {
      id: "30",
      category: "Characters", 
      label:  "Eric", 
      imgUrl: "src/assets/eric.jpg", 
      actor: "Jandino", 
      path: "/Characters/Eric"},
    {
      id: "31",
      category: "Characters", 
      label:  "Maggie", 
      imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRitLGbjcYLFLEPC3W2dUF_AUMIFrXS13c0jg&s", 
      actor: "Victoria Suárez Battán", 
      path:"/Characters/Maggie"
    },
    {
      id: "32",
      category: "Seasons", 
      label: "Season 1", 
      imgUrl: "https://cdn.moviefone.com/image-assets/66203/4JDmIzhNF7aMsDGlxVwkQ9kv9E6.jpg?d=360x540&q=30", 
      path: "/Seaasons/Season_1"},
    {
      id: "33",
      category: "Seasons", 
      label: "Season 2", 
      imgUrl: "https://image.tmdb.org/t/p/original/78CUmir4MDINMKdkUt4TmW5d7k4.jpg", 
      path: "/Seaasons/Season_2"
    },
    {
      id: "34",
      category: "Seasons", 
      label: "Season 3", 
      imgUrl: "https://image.tmdb.org/t/p/original/gODp9C6CI3khgatxOgmFW3WINXF.jpg", 
      path: "/Seaasons/Season_3"},
    {
      id: "35",
      category: "Seasons", 
      label: "Season 4", 
      imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTU1yoyYhsFad8KQSrS1dtHgrBu6IuAMCNJDw&s", 
      path: "/Seaasons/Season_4"},
    {
      id: "36",
       category: "Romances", label: "Luna and Matteo", imgUrl: LutteoImg, path: "/Romances/Lutteo"},
    {
      id: "37",
       category: "Romances", label: "Luna and Simón", imgUrl: LumonImg, path: "/Romances/Lumon"},
    {
      id: "38",
       category: "Romances", label: "Nina and Gastón", imgUrl: GastinaImg, path: "/Romances/Gastina"},
    {
      id: "39",
       category: "Romances", label: "Àmbar and Simón", imgUrl: SimbarImg, path: "/Romances/Simbar"},
    {
      id: "40",
       category: "Romances", label: "Pedro and Delfi", imgUrl: PelfiImg, path: "/Romances/Pelfi"},
    {
      id: "41",
       category: "Romances", label: "Nico and Jim", imgUrl: JicoImg, path: "/Romances/Jico"},
    {
      id: "42",
       category: "Romances", label: "Yam and Ramiro", imgUrl: YamiroImg, path: "/Romances/Yamiro"},
    {
      id: "43",
       category: "Romances", label: "Àmbar and Matteo", imgUrl: MambarImg, path: "/Romances/Mambar"},
    {
      id: "44",
       category: "Friendships", label: "Luna and Simón", imgUrl: LumonImg, path: "/Romances/Lumon"},
    {
      id: "45",
       category: "Friendships", label: "Luna and Nina", imgUrl: LuninaImg, path: "/Friendships/Luna_and_Nina"},
    {
      id: "46",
       category: "Friendships", label: "Jim and Yam", imgUrl: JimYamImg, path: "/Friendships/Jim_and_Yam"},
    {
      id: "47",
       category: "Friendships", label: "Matteo and Gastón", imgUrl: GasteoImg, path: "/Friendships/Gastón_and_Matteo"},
    {
      id: "48",
       category: "Friendships", label: "Ámbar, Delfi and Jazmín", imgUrl: ÁmbarDelfiJazmínImg, path: "/Friendships/Ámbar_Delfi_and_Jazmín"},
    {
      id: "49",
       category: "Friendships", label: "Nico, Pedro and Simòn", imgUrl: SimonPedroNicoImg, path: "/Friendships/Nico_Pedro_and_Simón"},
    {
      id: "50",
       category: "Friendships", label: "Matteo and Simón", imgUrl: SitteoImg, path: "/Friendships/Simón_and_Matteo"},
    {
      id: "51",
       category: "Friendships", label: "Àmbar and Emilia", imgUrl: ÁmbiliaImg,path:  "/Friendships/Ámbar_and_Emilia"},
    {
      id: "52",
       category: "Friendships", label: "Tino and Cato", imgUrl: TinoCatoImg, path: "/Friendships/Tino_and_Cato"},
    {
      id: "53",
       category: "Friendships", label:  "Ana and Mora", imgUrl: AnaMoraImg, path: "/Friendships/Ana_and_Mora"},
    {
    id: "1",
    imgUrl: "https://upload.wikimedia.org/wikipedia/en/0/04/Soy_Luna_soundtrack.jpg",
    path: "/Album/Soy_Luna (Album)",
    label: "Soy Luna (Album)",
    category: "Album",
    season: 1,
    nosongs: 12,
    release: "2016-02-26",
    songs: [
      {
        id: 1,
        label: "Alas",
        path: "/Album/Soy_Luna (Album)/Alas",
        artist: "Karol Sevilla",
        release: "2016-02-26",
        season: 1,
        album: "Soy Luna",
        img: "https://upload.wikimedia.org/wikipedia/en/0/04/Soy_Luna_soundtrack.jpg",
        spotifyUrl: "https://open.spotify.com/track/4wWo2EHTXBQJG2PvTHyrRd",
        ytUrl: "https://www.youtube.com/watch?v=Vc99pIcimio"
      },
      {
        id: 2,
        label: "Valiente",
        path: "/Album/Soy_Luna (Album)/Valiente",
        artist: "Michael Ronda",
        release: "2016-02-26",
        season: 1,
        album: "Soy Luna",
        img: "https://upload.wikimedia.org/wikipedia/en/0/04/Soy_Luna_soundtrack.jpg",
        spotifyUrl: "https://open.spotify.com/track/25x31n1U2nQIS9xHmDUKEF",
        ytUrl: "https://www.youtube.com/watch?v=ArWTbhgkH-A"
      },
      {
        id: 3,
        label: "Eres",
        path: "/Album/Soy_Luna (Album)/Eres",
        artist: "Karol Sevilla & Michael Ronda",
        release: "2016-02-26",
        season: 1,
        album: "Soy Luna",
        img: "https://upload.wikimedia.org/wikipedia/en/0/04/Soy_Luna_soundtrack.jpg",
        spotifyUrl: "https://open.spotify.com/track/5Rbi2OkoVaeXKggzLH9NZG",
        ytUrl: "https://www.youtube.com/watch?v=DUBCQS4cdf4"
      },
      {
        id: 4,
        label: "Prófugos",
        path: "/Album/Soy_Luna (Album)/Prófugos",
        artist: "Ruggero Pasquarelli & Valentina Zenere",
        release: "2016-02-26",
        season: 1,
        album: "Soy Luna",
        img: "https://upload.wikimedia.org/wikipedia/en/0/04/Soy_Luna_soundtrack.jpg",
        spotifyUrl: "https://open.spotify.com/track/22CI4H2HluhEgLO3PGOR2m",
        ytUrl: "https://www.youtube.com/watch?v=IOdTclyQHbc"
      },
      {
        id: 5,
        label: "Un destino",
        path: "/Album/Soy_Luna (Album)/Un_destino",
        artist: "Michael Ronda, Lionel Ferro & Gastón Vietto",
        release: "2016-02-26",
        season: 1,
        album: "Soy Luna",
        img: "https://upload.wikimedia.org/wikipedia/en/0/04/Soy_Luna_soundtrack.jpg",
        spotifyUrl: "https://open.spotify.com/track/0gCuB6ekC1z8OYAy5ojR35",
        ytUrl: "https://www.youtube.com/watch?v=3LV4fH1p3Aw"
      },
      {
        id: 6,
        label: "Sobre ruedas",
        path: "/Album/Soy_Luna (Album)/Sobre_ruedas",
        artist: "Female Cast",
        release: "2016-02-26",
        season: 1,
        album: "Soy Luna",
        img: "https://upload.wikimedia.org/wikipedia/en/0/04/Soy_Luna_soundtrack.jpg",
        spotifyUrl: "https://open.spotify.com/track/2DiLtJbVBGT8yjWVfHQyax",
        ytUrl: "https://www.youtube.com/watch?v=9j2W6Ge7-VU"
      },
      {
        id: 7,
        label: "Corazón",
        path: "/Album/Soy_Luna (Album)/Corazón",
        artist: "Agustín Bernasconi & Malena Ratner",
        release: "2016-02-26",
        season: 1,
        album: "Soy Luna",
        img: "https://upload.wikimedia.org/wikipedia/en/0/04/Soy_Luna_soundtrack.jpg",
        spotifyUrl: "https://open.spotify.com/track/6A5shXDBOOnoizJpGHDUoh",
        ytUrl: "https://www.youtube.com/watch?v=xiS8b7SSuPk"
      },
      {
        id: 8,
        label: "Mírame a mí",
        path: "/Album/Soy_Luna (Album)Mírame_a_mí",
        artist: "Valentina Zenere",
        release: "2016-02-26",
        season: 1,
        album: "Soy Luna",
        img: "https://upload.wikimedia.org/wikipedia/en/0/04/Soy_Luna_soundtrack.jpg",
        spotifyUrl: "https://open.spotify.com/track/0NOFUwXnBZFgHAKclrkgAF",
        ytUrl: "https://www.youtube.com/watch?v=kPX0mPb_Z_0"
      },
      {
        id: 9,
        label: "I'd Be Crazy",
        path: "/Album/Soy_Luna (Album)/I'd_Be_Crazy",
        artist: "Male Cast",
        release: "2016-02-26",
        season: 1,
        album: "Soy Luna",
        img: "https://upload.wikimedia.org/wikipedia/en/0/04/Soy_Luna_soundtrack.jpg",
        spotifyUrl: "https://open.spotify.com/track/1oy6FvwMAXA1V7AYrJfQcO",
        ytUrl: "https://www.youtube.com/watch?v=zSAluFDVE9o"
      },
      {
        id: 10,
        label: "Siento",
        path: "/Album/Soy_Luna (Album)/Siento",
        artist: "Ruggero Pasquarelli",
        release: "2016-02-26",
        season: 1,
        album: "Soy Luna",
        img: "https://upload.wikimedia.org/wikipedia/en/0/04/Soy_Luna_soundtrack.jpg",
        spotifyUrl: "https://open.spotify.com/track/7mi6yDxL2Fo9yafZkPCw2g",
        ytUrl: "https://www.youtube.com/watch?v=yTwljaoCQsE"
      },
      {
        id: 11,
        label: "Invisibles",
        path: "/Album/Soy_Luna (Album)/Invisibles",
        artist: "Michael Ronda, Lionel Ferro & Gastón Vietto",
        release: "2016-02-26",
        season: 1,
        album: "Soy Luna",
        img: "https://upload.wikimedia.org/wikipedia/en/0/04/Soy_Luna_soundtrack.jpg",
        spotifyUrl: "https://open.spotify.com/track/52fTTDnsVZRde8ROjgOaic",
        ytUrl: "https://www.youtube.com/watch?v=GaNdEEjvb-E"
      },
      {
        id: 12,
        label: "Camino",
        path: "/Album/Soy_Luna (Album)/Camino",
        artist: "Cast",
        release: "2016-02-26",
        season: 1,
        album: "Soy Luna",
        img: "https://upload.wikimedia.org/wikipedia/en/0/04/Soy_Luna_soundtrack.jpg",
        spotifyUrl: "https://open.spotify.com/track/5S043XSYNK90SyEPJ3yJjl",
        ytUrl: "https://www.youtube.com/watch?v=aUOjXqtrQL4"
      }
    ]
  },
  {
    id: "2",
    imgUrl: "https://upload.wikimedia.org/wikipedia/en/0/0b/Soy_Luna_-_M%C3%BAsica_en_ti.jpg",
    path: "/Album/Musica_en_ti (Album)",
    label: "Música en ti (Album)",
    category: "Album",
    season: 1,
    nosongs: 13,
    release: "2016-08-26",
    songs: [
      { id: 13, path: "/Album/Musica_en_ti (Album)/Vuelo", label: "Vuelo", artist: "Cast", release: "2016-08-26", season: 1, album: "Música en ti", img: "https://upload.wikimedia.org/wikipedia/en/0/0b/Soy_Luna_-_M%C3%BAsica_en_ti.jpg", spotifyUrl: "", ytUrl: "" },
      { id: 14, path: "/Album/Musica_en_ti (Album)/Musica_en_ti", label: "Música en ti", artist: "Karol Sevilla", release: "2016-08-26", season: 1, album: "Música en ti", img: "https://upload.wikimedia.org/wikipedia/en/0/0b/Soy_Luna_-_M%C3%BAsica_en_ti.jpg", spotifyUrl: "", ytUrl: "" },
      { id: 15, path: "/Album/Musica_en_ti (Album)/A_rodar_mi_vida", label: "A rodar mi vida", artist: "Cast", release: "2016-08-26", season: 1, album: "Música en ti", img: "https://upload.wikimedia.org/wikipedia/en/0/0b/Soy_Luna_-_M%C3%BAsica_en_ti.jpg", spotifyUrl: "", ytUrl: "" },
      { id: 16, path: "/Album/Musica_en_ti (Album)/Nada_ni_nadie", label: "Nada ni nadie", artist: "Ruggero Pasquarelli", release: "2016-08-26", season: 1, album: "Música en ti", img: "https://upload.wikimedia.org/wikipedia/en/0/0b/Soy_Luna_-_M%C3%BAsica_en_ti.jpg", spotifyUrl: "", ytUrl: "" },
      { id: 17, path: "/Album/Musica_en_ti (Album)/Chicas_así", label: "Chicas así", artist: "Valentina Zenere, Malena Ratner & Katja Martínez", release: "2016-08-26", season: 1, album: "Música en ti", img: "https://upload.wikimedia.org/wikipedia/en/0/0b/Soy_Luna_-_M%C3%BAsica_en_ti.jpg", spotifyUrl: "", ytUrl: "" },
      { id: 18, path: "/Album/Musica_en_ti (Album)/Tengo_un_corazón", label: "Tengo un corazón", artist: "Carolina Kopelioff", release: "2016-08-26", season: 1, album: "Música en ti", img: "https://upload.wikimedia.org/wikipedia/en/0/0b/Soy_Luna_-_M%C3%BAsica_en_ti.jpg", spotifyUrl: "", ytUrl: "" },
      { id: 19, path: "/Album/Musica_en_ti (Album)/Qué_más_da", label: "Qué más da", artist: "Karol Sevilla & Ruggero Pasquarelli", release: "2016-08-26", season: 1, album: "Música en ti", img: "https://upload.wikimedia.org/wikipedia/en/0/0b/Soy_Luna_-_M%C3%BAsica_en_ti.jpg", spotifyUrl: "", ytUrl: "" },
      { id: 20, path: "/Album/Musica_en_ti (Album)/Sin_fronteras", label: "Sin fronteras", artist: "Karol Sevilla & Carolina Kopelioff", release: "2016-08-26", season: 1, album: "Música en ti", img: "https://upload.wikimedia.org/wikipedia/en/0/0b/Soy_Luna_-_M%C3%BAsica_en_ti.jpg", spotifyUrl: "", ytUrl: "" },
      { id: 21, path: "/Album/Musica_en_ti (Album)/Eres", label: "Eres (Radio Disney Vivo)", artist: "Karol Sevilla, Ruggero Pasquarelli & Michael Ronda", release: "2016-08-26", season: 1, album: "Música en ti", img: "https://upload.wikimedia.org/wikipedia/en/0/0b/Soy_Luna_-_M%C3%BAsica_en_ti.jpg", spotifyUrl: "", ytUrl: "" },
      { id: 22, path: "/Album/Musica_en_ti (Album)/Valiente", label: "Valiente (Radio Disney Vivo)", artist: "Karol Sevilla, Michael Ronda, Gastón Vietto & Lionel Ferro", release: "2016-08-26", season: 1, album: "Música en ti", img: "https://upload.wikimedia.org/wikipedia/en/0/0b/Soy_Luna_-_M%C3%BAsica_en_ti.jpg", spotifyUrl: "", ytUrl: "" },
      { id: 23, path: "/Album/Musica_en_ti (Album)/Alas", label: "Alas (Radio Disney Vivo)", artist: "Cast", release: "2016-08-26", season: 1, album: "Música en ti", img: "https://upload.wikimedia.org/wikipedia/en/0/0b/Soy_Luna_-_M%C3%BAsica_en_ti.jpg", spotifyUrl: "", ytUrl: "" },
      { id: 24, path: "/Album/Musica_en_ti (Album)/A_rodar_mi_vida", label: "A rodar mi vida (Acoustic)", artist: "Chiara Parravicini", release: "2016-08-26", season: 1, album: "Música en ti", img: "https://upload.wikimedia.org/wikipedia/en/0/0b/Soy_Luna_-_M%C3%BAsica_en_ti.jpg", spotifyUrl: "", ytUrl: "" }
    ]
  },
  {
    id: "3",
    imgUrl: "https://upload.wikimedia.org/wikipedia/en/4/40/La_vida_es_un_sue%C3%B1o.jpg",
    path: "/Album/La_vida_es_un_sueño (Album)",
    label: "La vida es un sueño part 1 & 2 (Album)",
    category: "Album",
    season: 2,
    nosongs: 25,
    release: "2017-03-03",
    songs: [
      { id: 25, path: "/Album/La_vida_es_un_sueño (Album)/Siempre_juntos", label: "Siempre juntos", artist: "Karol Sevilla", release: "2017-03-03", season: 2, album: "La vida es un sueño", img: "https://upload.wikimedia.org/wikipedia/en/4/40/La_vida_es_un_sue%C3%B1o.jpg", spotifyUrl: "", ytUrl: "" },
      { id: 26, path: "/Album/La_vida_es_un_sueño (Album)/Alzo_mi_bandera", label: "Alzo mi bandera", artist: "Michael Ronda, Gastón Vietto & Lionel Ferro", release: "2017-03-03", season: 2, album: "La vida es un sueño", img: "https://upload.wikimedia.org/wikipedia/en/4/40/La_vida_es_un_sue%C3%B1o.jpg", spotifyUrl: "", ytUrl: "" },
      { id: 27, path: "/Album/La_vida_es_un_sueño (Album)/La_vida_es_un_sueño", label: "La vida es un sueño", artist: "Karol Sevilla", release: "2017-03-03", season: 2, album: "La vida es un sueño", img: "https://upload.wikimedia.org/wikipedia/en/4/40/La_vida_es_un_sue%C3%B1o.jpg", spotifyUrl: "", ytUrl: "" },
      { id: 28, path: "/Album/La_vida_es_un_sueño (Album)/Fush,_¡Te_vas", label: "Fush, ¡Te vas!", artist: "Katja Martínez", release: "2017-03-03", season: 2, album: "La vida es un sueño", img: "https://upload.wikimedia.org/wikipedia/en/4/40/La_vida_es_un_sue%C3%B1o.jpg", spotifyUrl: "", ytUrl: "" },
      { id: 29, path: "/Album/La_vida_es_un_sueño (Album)/¿Cómo_me_ves?", label: "¿Cómo me ves?", artist: "Valentina Zenere", release: "2017-03-03", season: 2, album: "La vida es un sueño", img: "https://upload.wikimedia.org/wikipedia/en/4/40/La_vida_es_un_sue%C3%B1o.jpg", spotifyUrl: "", ytUrl: "" },
      { id: 30, path: "/Album/La_vida_es_un_sueño (Album)/Mitad_y_mitad", label: "Mitad y mitad", artist: "Agustín Bernasconi & Carolina Kopelioff", release: "2017-03-03", season: 2, album: "La vida es un sueño", img: "https://upload.wikimedia.org/wikipedia/en/4/40/La_vida_es_un_sue%C3%B1o.jpg", spotifyUrl: "", ytUrl: "" },
      { id: 31, path: "/Album/La_vida_es_un_sueño (Album)/Valiente", label: "Valiente", artist: "Cast", release: "2017-03-03", season: 2, album: "La vida es un sueño", img: "https://upload.wikimedia.org/wikipedia/en/4/40/La_vida_es_un_sue%C3%B1o.jpg", spotifyUrl: "", ytUrl: "" },
      { id: 32, path: "/Album/La_vida_es_un_sueño (Album)/Honey_Funny", label: "Honey Funny", artist: "Chiara Parravicini, Ana Jara & Jorge López", release: "2017-03-03", season: 2, album: "La vida es un sueño", img: "https://upload.wikimedia.org/wikipedia/en/4/40/La_vida_es_un_sue%C3%B1o.jpg", spotifyUrl: "", ytUrl: "" },
      { id: 33, path: "/Album/La_vida_es_un_sueño (Album)/Linda", label: "Linda", artist: "Michael Ronda, Gastón Vietto & Lionel Ferro", release: "2017-03-03", season: 2, album: "La vida es un sueño", img: "https://upload.wikimedia.org/wikipedia/en/4/40/La_vida_es_un_sue%C3%B1o.jpg", spotifyUrl: "", ytUrl: "" },
      { id: 34, path: "/Album/La_vida_es_un_sueño (Album)/Cuenta_conmigo", label: "Cuenta conmigo", artist: "Cast", release: "2017-03-03", season: 2, album: "La vida es un sueño", img: "https://upload.wikimedia.org/wikipedia/en/4/40/La_vida_es_un_sue%C3%B1o.jpg", spotifyUrl: "", ytUrl: "" },
      { id: 35, path: "/Album/La_vida_es_un_sueño (Album)/Vives_en_mí", label: "Vives en mí", artist: "Karol Sevilla & Ruggero Pasquarelli", release: "2017-03-03", season: 2, album: "La vida es un sueño", img: "https://upload.wikimedia.org/wikipedia/en/4/40/La_vida_es_un_sue%C3%B1o.jpg", spotifyUrl: "", ytUrl: "" },
      { id: 36, path: "/Album/La_vida_es_un_sueño (Album)/I've_Got_a_Feeling", label: "I've Got a Feeling", artist: "Cast", release: "2017-03-03", season: 2, album: "La vida es un sueño", img: "https://upload.wikimedia.org/wikipedia/en/4/40/La_vida_es_un_sue%C3%B1o.jpg", spotifyUrl: "", ytUrl: "" },
      { id: 37, path: "/Album/La_vida_es_un_sueño (Album)/Princesa", label: "Princesa", artist: "Ruggero Pasquarelli", release: "2017-03-03", season: 2, album: "La vida es un sueño", img: "https://upload.wikimedia.org/wikipedia/en/4/40/La_vida_es_un_sue%C3%B1o.jpg", spotifyUrl: "", ytUrl: "" },
      { id: 38, path: "/Album/La_vida_es_un_sueño (Album)/Footloose", label: "Footloose", artist: "Cast", release: "2017-03-03", season: 2, album: "La vida es un sueño", img: "https://upload.wikimedia.org/wikipedia/en/4/40/La_vida_es_un_sue%C3%B1o.jpg", spotifyUrl: "", ytUrl: "" },
      { id: 39, path: "/Album/La_vida_es_un_sueño (Album)/Sólo_para_ti", label: "Sólo para ti", artist: "Karol Sevilla", release: "2017-03-03", season: 2, album: "La vida es un sueño", img: "https://upload.wikimedia.org/wikipedia/en/4/40/La_vida_es_un_sue%C3%B1o.jpg", spotifyUrl: "", ytUrl: "" },
      { id: 40, path: "/Album/La_vida_es_un_sueño (Album)/Catch_Me_If_You_Can", label: "Catch Me If You Can", artist: "Valentina Zenere", release: "2017-03-03", season: 2, album: "La vida es un sueño", img: "https://upload.wikimedia.org/wikipedia/en/4/40/La_vida_es_un_sue%C3%B1o.jpg", spotifyUrl: "", ytUrl: "" },
      { id: 41, path: "/Album/La_vida_es_un_sueño (Album)/Pienso", label: "Pienso", artist: "Michael Ronda, Gastón Vietto & Lionel Ferro", release: "2017-03-03", season: 2, album: "La vida es un sueño", img: "https://upload.wikimedia.org/wikipedia/en/4/40/La_vida_es_un_sue%C3%B1o.jpg", spotifyUrl: "", ytUrl: "" },
      { id: 42, path: "/Album/La_vida_es_un_sueño (Album)/Andaremos", label: "Andaremos", artist: "Karol Sevilla & Michael Ronda", release: "2017-03-03", season: 2, album: "La vida es un sueño", img: "https://upload.wikimedia.org/wikipedia/en/4/40/La_vida_es_un_sue%C3%B1o.jpg", spotifyUrl: "", ytUrl: "" },
      { id: 43, path: "/Album/La_vida_es_un_sueño (Album)/Allá_voy", label: "Allá voy", artist: "Ruggero Pasquarelli", release: "2017-03-03", season: 2, album: "La vida es un sueño", img: "https://upload.wikimedia.org/wikipedia/en/4/40/La_vida_es_un_sue%C3%B1o.jpg", spotifyUrl: "", ytUrl: "" },
      { id: 44, path: "/Album/La_vida_es_un_sueño (Album)/No_te_pido_mucho", label: "No te pido mucho", artist: "Karol Sevilla", release: "2017-03-03", season: 2, album: "La vida es un sueño", img: "https://upload.wikimedia.org/wikipedia/en/4/40/La_vida_es_un_sue%C3%B1o.jpg", spotifyUrl: "", ytUrl: "" },
      { id: 45, path: "/Album/La_vida_es_un_sueño (Album)/Stranger", label: "Stranger", artist: "Ruggero Pasquarelli", release: "2017-03-03", season: 2, album: "La vida es un sueño", img: "https://upload.wikimedia.org/wikipedia/en/4/40/La_vida_es_un_sue%C3%B1o.jpg", spotifyUrl: "", ytUrl: "" },
      { id: 46, path: "/Album/La_vida_es_un_sueño (Album)/Aquí_estoy", label: "Aquí estoy", artist: "Agustín Bernasconi & Ruggero Pasquarelli", release: "2017-03-03", season: 2, album: "La vida es un sueño", img: "https://upload.wikimedia.org/wikipedia/en/4/40/La_vida_es_un_sue%C3%B1o.jpg", spotifyUrl: "", ytUrl: "" },
      { id: 47, path: "/Album/La_vida_es_un_sueño (Album)/Yes,_I_Do", label: "Yes, I Do", artist: "Chiara Parravicini", release: "2017-03-03", season: 2, album: "La vida es un sueño", img: "https://upload.wikimedia.org/wikipedia/en/4/40/La_vida_es_un_sue%C3%B1o.jpg", spotifyUrl: "", ytUrl: "" },
      { id: 48, path: "/Album/La_vida_es_un_sueño (Album)/Yo_quisiera", label: "Yo quisiera", artist: "Michael Ronda", release: "2017-03-03", season: 2, album: "La vida es un sueño", img: "https://upload.wikimedia.org/wikipedia/en/4/40/La_vida_es_un_sue%C3%B1o.jpg", spotifyUrl: "", ytUrl: "" },
      { id: 49, path: "/Album/La_vida_es_un_sueño (Album)/Siempre_juntos", label: "Siempre juntos (group version)", artist: "Cast", release: "2017-03-03", season: 2, album: "La vida es un sueño", img: "https://upload.wikimedia.org/wikipedia/en/4/40/La_vida_es_un_sue%C3%B1o.jpg", spotifyUrl: "", ytUrl: "" }
    ]
  },
  {
    id: "4",
    imgUrl: "https://i.scdn.co/image/ab67616d0000b273effbb11a16be922e05017e98",
    path: "/Album/Modo_Amar (Album)",
    label: "Modo Amar (Album)",
    category: "Album",
    season: 3,
    nosongs: 19,
    release: "2018-04-06",
    songs: [
      { id: 50, path: "/Album/Modo_Amar (Album)/Modo_amar", label: "Modo amar", artist: "Cast", release: "2018-04-06", season: 3, album: "Modo Amar", img: "https://i.scdn.co/image/ab67616d0000b273effbb11a16be922e05017e98", spotifyUrl: "", ytUrl: "" },
      { id: 51, path: "/Album/Modo_Amar (Album)/Soy_yo", label: "Soy yo", artist: "Karol Sevilla", release: "2018-04-06", season: 3, album: "Modo Amar", img: "https://i.scdn.co/image/ab67616d0000b273effbb11a16be922e05017e98", spotifyUrl: "", ytUrl: "" },
      { id: 52, path: "/Album/Modo_Amar (Album)/Quiero_verte_sonreir", label: "Quiero verte sonreir", artist: "Ruggero Pasquarelli", release: "2018-04-06", season: 3, album: "Modo Amar", img: "https://i.scdn.co/image/ab67616d0000b273effbb11a16be922e05017e98", spotifyUrl: "", ytUrl: "" },
      { id: 53, path: "/Album/Modo_Amar (Album)/Claroscuro", label: "Claroscuro", artist: "Valentina Zenere", release: "2018-04-06", season: 3, album: "Modo Amar", img: "https://i.scdn.co/image/ab67616d0000b273effbb11a16be922e05017e98", spotifyUrl: "", ytUrl: "" },
      { id: 54, path: "/Album/Modo_Amar (Album)/Tiempo_de_amor", label: "Tiempo de amor", artist: "Michael Ronda", release: "2018-04-06", season: 3, album: "Modo Amar", img: "https://i.scdn.co/image/ab67616d0000b273effbb11a16be922e05017e98", spotifyUrl: "", ytUrl: "" },
      { id: 55, path: "/Album/Modo_Amar (Album)/Tu_cárcel", label: "Tu cárcel", artist: "Karol Sevilla & Michael Ronda", release: "2018-04-06", season: 3, album: "Modo Amar", img: "https://i.scdn.co/image/ab67616d0000b273effbb11a16be922e05017e98", spotifyUrl: "", ytUrl: "" },
      { id: 56, path: "/Album/Modo_Amar (Album)/Despierta_mi_mundo", label: "Despierta mi mundo", artist: "Karol Sevilla, Ruggero Pasquarelli, Michael Ronda, Ana Jara, Chiara Parravicini, Malena Ratner & Katja Martínez", release: "2018-04-06", season: 3, album: "Modo Amar", img: "https://i.scdn.co/image/ab67616d0000b273effbb11a16be922e05017e98", spotifyUrl: "", ytUrl: "" },
      { id: 57, path: "/Album/Modo_Amar (Album)/Quédate", label: "Quédate", artist: "Karol Sevilla & Ruggero Pasquarelli", release: "2018-04-06", season: 3, album: "Modo Amar", img: "https://i.scdn.co/image/ab67616d0000b273effbb11a16be922e05017e98", spotifyUrl: "", ytUrl: "" },
      { id: 58, path: "/Album/Modo_Amar (Album)/Solos", label: "Solos", artist: "Valentina Zenere & Michael Ronda", release: "2018-04-06", season: 3, album: "Modo Amar", img: "https://i.scdn.co/image/ab67616d0000b273effbb11a16be922e05017e98", spotifyUrl: "", ytUrl: "" },
      { id: 59, path: "/Album/Modo_Amar (Album)/Decirte_lo_que_siento", label: "Decirte lo que siento", artist: "Gastón Vietto", release: "2018-04-06", season: 3, album: "Modo Amar", img: "https://i.scdn.co/image/ab67616d0000b273effbb11a16be922e05017e98", spotifyUrl: "", ytUrl: "" },
      { id: 60, path: "/Album/Modo_Amar (Album)/Mi_corazón_hace_wow_wow", label: "Mi corazón hace wow wow", artist: "Jandino", release: "2018-04-06", season: 3, album: "Modo Amar", img: "https://i.scdn.co/image/ab67616d0000b273effbb11a16be922e05017e98", spotifyUrl: "", ytUrl: "" },
      { id: 61, path: "/Album/Modo_Amar (Album)/Nada_me_podrá_parar", label: "Nada me podrá parar", artist: "Karol Sevilla", release: "2018-04-06", season: 3, album: "Modo Amar", img: "https://i.scdn.co/image/ab67616d0000b273effbb11a16be922e05017e98", spotifyUrl: "", ytUrl: "" },
      { id: 62, path: "/Album/Modo_Amar (Album)/Si_lo_sueñas_claro", label: "Si lo sueñas claro", artist: "Cast", release: "2018-04-06", season: 3, album: "Modo Amar", img: "https://i.scdn.co/image/ab67616d0000b273effbb11a16be922e05017e98", spotifyUrl: "", ytUrl: "" },
      { id: 63, path: "/Album/Modo_Amar (Album)/Esta_noche_no_paro", label: "Esta noche no paro", artist: "Ruggero Pasquarelli", release: "2018-04-06", season: 3, album: "Modo Amar", img: "https://i.scdn.co/image/ab67616d0000b273effbb11a16be922e05017e98", spotifyUrl: "", ytUrl: "" },
      { id: 64, path: "/Album/Modo_Amar (Album)/Creyendo_en_mí", label: "Creyendo en mí", artist: "Chiara Parravicini", release: "2018-04-06", season: 3, album: "Modo Amar", img: "https://i.scdn.co/image/ab67616d0000b273effbb11a16be922e05017e98", spotifyUrl: "", ytUrl: "" },
      { id: 65, path: "/Album/Modo_Amar (Album)/Nadie_somo_tú", label: "Nadie somo tú", artist: "Male Cast", release: "2018-04-06", season: 3, album: "Modo Amar", img: "https://i.scdn.co/image/ab67616d0000b273effbb11a16be922e05017e98", spotifyUrl: "", ytUrl: "" },
      { id: 66, path: "/Album/Modo_Amar (Album)/Mano_a_mano", label: "Mano a mano", artist: "Female Cast", release: "2018-04-06", season: 3, album: "Modo Amar", img: "https://i.scdn.co/image/ab67616d0000b273effbb11a16be922e05017e98", spotifyUrl: "", ytUrl: "" },
      { id: 67, path: "/Album/Modo_Amar (Album)/Borrar tu mirada", label: "Borrar tu mirada", artist: "Karol Sevilla, Carolina Kopelioff, Ana Jara & Chiara Parravicini", release: "2018-04-06", season: 3, album: "Modo Amar", img: "https://i.scdn.co/image/ab67616d0000b273effbb11a16be922e05017e98", spotifyUrl: "", ytUrl: "" },
      { id: 68, path: "/Album/Modo_Amar (Album)/Todo puede cambiar", label: "Todo puede cambiar", artist: "Cast", release: "2018-04-06", season: 3, album: "Modo Amar", img: "https://i.scdn.co/image/ab67616d0000b273effbb11a16be922e05017e98", spotifyUrl: "", ytUrl: "" }
    ]
  }

]
